#ifndef ETH_XGMAC_REG_H
#define ETH_XGMAC_REG_H

#include <nuttx/bits.h>
#include <stdint.h>
#include <stdbool.h>

#define MAC_TX_CONFIGURATION      0x0
#define MAC_TX_CONFIGURATION_TE   BIT(0)
#define MAC_TX_CONFIGURATION_DDIC BIT(1)
#define MAC_TX_CONFIGURATION_ISM  BIT(3)
#define MAC_TX_CONFIGURATION_ISR  GENMASK(7, 4)
#define MAC_TX_CONFIGURATION_IPG  GENMASK(10, 8)
#define MAC_TX_CONFIGURATION_IFP  BIT(11)
#define MAC_TX_CONFIGURATION_TC   BIT(12)
#define MAC_TX_CONFIGURATION_LUD  BIT(13)
#define MAC_TX_CONFIGURATION_JD   BIT(16)
#define MAC_TX_CONFIGURATION_SARC GENMASK(22, 20)
#define MAC_TX_CONFIGURATION_SS   GENMASK(31, 29)

#define MAC_RX_CONFIGURATION        0x4
#define MAC_RX_CONFIGURATION_RE     BIT(0)
#define MAC_RX_CONFIGURATION_ACS    BIT(1)
#define MAC_RX_CONFIGURATION_CST    BIT(2)
#define MAC_RX_CONFIGURATION_DCRCC  BIT(3)
#define MAC_RX_CONFIGURATION_SPEN   BIT(4)
#define MAC_RX_CONFIGURATION_USP    BIT(5)
#define MAC_RX_CONFIGURATION_GPSLCE BIT(6)
#define MAC_RX_CONFIGURATION_WD     BIT(7)
#define MAC_RX_CONFIGURATION_JE     BIT(8)
#define MAC_RX_CONFIGURATION_IPC    BIT(9)
#define MAC_RX_CONFIGURATION_LM     BIT(10)
#define MAC_RX_CONFIGURATION_S2KP   BIT(11)
#define MAC_RX_CONFIGURATION_HDSMS  GENMASK(14, 12)
#define MAC_RX_CONFIGURATION_GPSL   GENMASK(29, 16)

#define MAC_PACKET_FILTER        0x8
#define MAC_PACKET_FILTER_PR     BIT(0)
#define MAC_PACKET_FILTER_DAIF   BIT(3)
#define MAC_PACKET_FILTER_PM     BIT(4)
#define MAC_PACKET_FILTER_DBF    BIT(5)
#define MAC_PACKET_FILTER_PCF    GENMASK(7, 6)
#define MAC_PACKET_FILTER_SAIF   BIT(8)
#define MAC_PACKET_FILTER_SAF    BIT(9)
#define MAC_PACKET_FILTER_DHLFRS GENMASK(12, 11)
#define MAC_PACKET_FILTER_VTFE   BIT(16)
#define MAC_PACKET_FILTER_IPFE   BIT(20)
#define MAC_PACKET_FILTER_DNTU   BIT(21)
#define MAC_PACKET_FILTER_RA     BIT(31)
#define MAC_WD_JB_TIMEOUT        0xC
#define MAC_WD_JB_TIMEOUT_WTO    GENMASK(3, 0)
#define MAC_WD_JB_TIMEOUT_PWE    BIT(8)
#define MAC_WD_JB_TIMEOUT_JTO    GENMASK(19, 16)
#define MAC_WD_JB_TIMEOUT_PJE    BIT(24)

#define MAC_VLAN_TAG         0x50
#define MAC_VLAN_TAG_VL      GENMASK(15, 0)
#define MAC_VLAN_TAG_ETV     BIT(16)
#define MAC_VLAN_TAG_VTIM    BIT(17)
#define MAC_VLAN_TAG_ESVL    BIT(18)
#define MAC_VLAN_TAG_ERSVLM  BIT(19)
#define MAC_VLAN_TAG_DOVLTC  BIT(20)
#define MAC_VLAN_TAG_EVLS    GENMASK(22, 21)
#define MAC_VLAN_TAG_EVLRXS  BIT(24)
#define MAC_VLAN_TAG_VTHM    BIT(25)
#define MAC_VLAN_TAG_EDVLP   BIT(26)
#define MAC_VLAN_TAG_ERIVLT  BIT(27)
#define MAC_VLAN_TAG_EIVLS   GENMASK(29, 28)
#define MAC_VLAN_TAG_EIVLRXS BIT(31)

#define MAC_VLAN_TAG_CTRL         0x50
#define MAC_VLAN_TAG_CTRL_OB      BIT(0)
#define MAC_VLAN_TAG_CTRL_CT      BIT(1)
#define MAC_VLAN_TAG_CTRL_OFS     GENMASK(6, 2)
#define MAC_VLAN_TAG_CTRL_ETV     BIT(16)
#define MAC_VLAN_TAG_CTRL_VTIM    BIT(17)
#define MAC_VLAN_TAG_CTRL_ESVL    BIT(18)
#define MAC_VLAN_TAG_CTRL_ERSVLM  BIT(19)
#define MAC_VLAN_TAG_CTRL_DOVLTC  BIT(20)
#define MAC_VLAN_TAG_CTRL_EVLS    GENMASK(22, 21)
#define MAC_VLAN_TAG_CTRL_EVLRXS  BIT(24)
#define MAC_VLAN_TAG_CTRL_VTHM    BIT(25)
#define MAC_VLAN_TAG_CTRL_EDVLP   BIT(26)
#define MAC_VLAN_TAG_CTRL_ERIVLT  BIT(27)
#define MAC_VLAN_TAG_CTRL_EIVLS   GENMASK(29, 28)
#define MAC_VLAN_TAG_CTRL_EIVLRXS BIT(31)

#define MAC_VLAN_TAG_DATA         0x54
#define MAC_VLAN_TAG_DATA_VID     GENMASK(15, 0)
#define MAC_VLAN_TAG_DATA_VEN     BIT(16)
#define MAC_VLAN_TAG_DATA_ETV     BIT(17)
#define MAC_VLAN_TAG_DATA_DOVLTC  BIT(18)
#define MAC_VLAN_TAG_DATA_ERSVLM  BIT(19)
#define MAC_VLAN_TAG_DATA_ERIVLT  BIT(20)
#define MAC_VLAN_TAG_DATA_DMACHEN BIT(24)
#define MAC_VLAN_TAG_DATA_DMACHN  GENMASK(27, 25)

#define MAC_VLAN_HASH_TABLE      0x58
#define MAC_VLAN_HASH_TABLE_VLHT GENMASK(15, 0)

#define MAC_VLAN_INCL      0x60
#define MAC_VLAN_INCL_VLT  GENMASK(15, 0)
#define MAC_VLAN_INCL_VLC  GENMASK(17, 16)
#define MAC_VLAN_INCL_VLP  BIT(18)
#define MAC_VLAN_INCL_CSVL BIT(19)
#define MAC_VLAN_INCL_VLTI BIT(20)
#define MAC_VLAN_INCL_CBTI BIT(21)
#define MAC_VLAN_INCL_ADDR GENMASK(26, 24)
#define MAC_VLAN_INCL_RDWR BIT(30)
#define MAC_VLAN_INCL_BUSY BIT(31)

#define MAC_INNER_VLAN_INCL      0x64
#define MAC_INNER_VLAN_INCL_VLT  GENMASK(15, 0)
#define MAC_INNER_VLAN_INCL_VLC  GENMASK(17, 16)
#define MAC_INNER_VLAN_INCL_VLP  BIT(18)
#define MAC_INNER_VLAN_INCL_CSVL BIT(19)
#define MAC_INNER_VLAN_INCL_VLTI BIT(20)

#define MAC_RX_ETH_TYPE_MATCH    0x6C
#define MAC_RX_ETH_TYPE_MATCH_ET GENMASK(15, 0)

#define MAC_Q0_TX_FLOW_CTRL               0x70
#define MAC_Q0_TX_FLOW_CTRL_FCB           BIT(0)
#define MAC_Q0_TX_FLOW_CTRL_TFE           BIT(1)
#define MAC_Q0_TX_FLOW_CTRL_PLT           GENMASK(6, 4)
#define MAC_Q0_TX_FLOW_CTRL_DZPQ          BIT(7)
#define MAC_Q0_TX_FLOW_CTRL_PT            GENMASK(31, 16)
#define MAC_RX_FLOW_CTRL                  0x90
#define MAC_RX_FLOW_CTRL_RFE              BIT(0)
#define MAC_RX_FLOW_CTRL_UP               BIT(1)
#define MAC_RXQ_CTRL4                     0x94
#define MAC_RXQ_CTRL4_UFFQE               BIT(0)
#define MAC_RXQ_CTRL4_UFFQ                GENMASK(3, 1)
#define MAC_RXQ_CTRL4_MFFQE               BIT(8)
#define MAC_RXQ_CTRL4_MFFQ                GENMASK(11, 9)
#define MAC_RXQ_CTRL4_VFFQE               BIT(16)
#define MAC_RXQ_CTRL4_VFFQ                GENMASK(19, 17)
#define MAC_RXQ_CTRL4_PMCBCQ              GENMASK(26, 24)
#define MAC_RXQ_CTRL4_UDC                 BIT(31)
#define MAC_RXQ_CTRL5                     0x98
#define MAC_RXQ_CTRL5_PRQSO               GENMASK(3, 0)
#define MAC_RXQ_CTRL0                     0xA0
#define MAC_RXQ_CTRL0_RXQ0EN              GENMASK(1, 0)
#define MAC_RXQ_CTRL0_RXQ1EN              GENMASK(3, 2)
#define MAC_RXQ_CTRL0_RXQ2EN              GENMASK(5, 4)
#define MAC_RXQ_CTRL0_RXQ3EN              GENMASK(7, 6)
#define MAC_RXQ_CTRL0_RXQ4EN              GENMASK(9, 8)
#define MAC_RXQ_CTRL0_RXQ5EN              GENMASK(11, 10)
#define MAC_RXQ_CTRL0_RXQ6EN              GENMASK(13, 12)
#define MAC_RXQ_CTRL0_RXQ7EN              GENMASK(15, 14)
#define MAC_RXQ_CTRL1                     0xA4
#define MAC_RXQ_CTRL1_UPQ                 GENMASK(3, 0)
#define MAC_RXQ_CTRL1_RQ                  GENMASK(7, 4)
#define MAC_RXQ_CTRL1_MCBCQ               GENMASK(11, 8)
#define MAC_RXQ_CTRL1_MCBCQEN             BIT(15)
#define MAC_RXQ_CTRL1_OMCBCQ              BIT(20)
#define MAC_RXQ_CTRL1_TPQC                GENMASK(22, 21)
#define MAC_RXQ_CTRL1_TACPQE              BIT(23)
#define MAC_RXQ_CTRL1_PTPQ                GENMASK(27, 24)
#define MAC_RXQ_CTRL1_AVCPQ               GENMASK(31, 28)
#define MAC_RXQ_CTRL2                     0xA8
#define MAC_RXQ_CTRL2_PSRQ0               GENMASK(7, 0)
#define MAC_RXQ_CTRL2_PSRQ1               GENMASK(15, 8)
#define MAC_RXQ_CTRL2_PSRQ2               GENMASK(23, 16)
#define MAC_RXQ_CTRL2_PSRQ3               GENMASK(31, 24)
#define MAC_RXQ_CTRL3                     0xAC
#define MAC_RXQ_CTRL3_PSRQ4               GENMASK(7, 0)
#define MAC_RXQ_CTRL3_PSRQ5               GENMASK(15, 8)
#define MAC_RXQ_CTRL3_PSRQ6               GENMASK(23, 16)
#define MAC_RXQ_CTRL3_PSRQ7               GENMASK(31, 24)
#define MAC_INTERRUPT_STATUS              0xB0
#define MAC_INTERRUPT_STATUS_LSI          BIT(0)
#define MAC_INTERRUPT_STATUS_SMI          BIT(1)
#define MAC_INTERRUPT_STATUS_PMTIS        BIT(4)
#define MAC_INTERRUPT_STATUS_LPIIS        BIT(5)
#define MAC_INTERRUPT_STATUS_MMCRXIS      BIT(9)
#define MAC_INTERRUPT_STATUS_MMCTXIS      BIT(10)
#define MAC_INTERRUPT_STATUS_MMCRXIPIS    BIT(11)
#define MAC_INTERRUPT_STATUS_TSIS         BIT(12)
#define MAC_INTERRUPT_STATUS_TXESIS       BIT(13)
#define MAC_INTERRUPT_STATUS_RXESIS       BIT(14)
#define MAC_INTERRUPT_STATUS_GPIIS        BIT(15)
#define MAC_INTERRUPT_STATUS_FPEIS        BIT(16)
#define MAC_INTERRUPT_STATUS_MFTIS        BIT(17)
#define MAC_INTERRUPT_STATUS_MFRIS        BIT(18)
#define MAC_INTERRUPT_STATUS_PCIS         BIT(23)
#define MAC_INTERRUPT_STATUS_LS           GENMASK(25, 24)
#define MAC_INTERRUPT_ENABLE              0xB4
#define MAC_INTERRUPT_ENABLE_LSIE         BIT(0)
#define MAC_INTERRUPT_ENABLE_PMTIE        BIT(4)
#define MAC_INTERRUPT_ENABLE_LPIIE        BIT(5)
#define MAC_INTERRUPT_ENABLE_TSIE         BIT(12)
#define MAC_INTERRUPT_ENABLE_TXESIE       BIT(13)
#define MAC_INTERRUPT_ENABLE_RXESIE       BIT(14)
#define MAC_INTERRUPT_ENABLE_FPEIE        BIT(15)
#define MAC_RX_TX_STATUS                  0xB8
#define MAC_RX_TX_STATUS_TJT              BIT(0)
#define MAC_RX_TX_STATUS_NCARR            BIT(1)
#define MAC_RX_TX_STATUS_LCARR            BIT(2)
#define MAC_RX_TX_STATUS_EXDEF            BIT(3)
#define MAC_RX_TX_STATUS_LCOL             BIT(4)
#define MAC_RX_TX_STATUS_EXCOL            BIT(5)
#define MAC_RX_TX_STATUS_RWT              BIT(8)
#define MAC_RX_TX_STATUS_IHE              BIT(12)
#define MAC_RX_TX_STATUS_PCE              BIT(13)
#define MAC_PMT_CONTROL_STATUS            0xC0
#define MAC_PMT_CONTROL_STATUS_PWRDWN     BIT(0)
#define MAC_PMT_CONTROL_STATUS_MGKPKTEN   BIT(1)
#define MAC_PMT_CONTROL_STATUS_RWKPKTEN   BIT(2)
#define MAC_PMT_CONTROL_STATUS_MGKPRCVD   BIT(5)
#define MAC_PMT_CONTROL_STATUS_RWKPRCVD   BIT(6)
#define MAC_PMT_CONTROL_STATUS_GLBLUCAST  BIT(9)
#define MAC_PMT_CONTROL_STATUS_RWKPFE     BIT(10)
#define MAC_PMT_CONTROL_STATUS_RWKPTR     GENMASK(28, 24)
#define MAC_PMT_CONTROL_STATUS_RWKFILTRST BIT(31)
#define MAC_RWK_PACKET_FILTER             0xC4
#define MAC_LPI_CONTROL_STATUS            0xD0
#define MAC_LPI_CONTROL_STATUS_TLPIEN     BIT(0)
#define MAC_LPI_CONTROL_STATUS_TLPIEX     BIT(1)
#define MAC_LPI_CONTROL_STATUS_RLPIEN     BIT(2)
#define MAC_LPI_CONTROL_STATUS_RLPIEX     BIT(3)
#define MAC_LPI_CONTROL_STATUS_TLPIST     BIT(8)
#define MAC_LPI_CONTROL_STATUS_RLPIST     BIT(9)
#define MAC_LPI_CONTROL_STATUS_LPITXEN    BIT(16)
#define MAC_LPI_CONTROL_STATUS_PLS        BIT(17)
#define MAC_LPI_CONTROL_STATUS_PLSDIS     BIT(18)
#define MAC_LPI_CONTROL_STATUS_LPITXA     BIT(19)
#define MAC_LPI_CONTROL_STATUS_LPIATE     BIT(20)
#define MAC_LPI_CONTROL_STATUS_LPITCSE    BIT(21)
#define MAC_LPI_TIMERS_CONTROL            0xD4
#define MAC_LPI_TIMERS_CONTROL_TWT        GENMASK(15, 0)
#define MAC_LPI_TIMERS_CONTROL_LST        GENMASK(25, 16)
#define MAC_LPI_AUTO_ENTRY_TIMER          0xD8
#define MAC_LPI_AUTO_ENTRY_TIMER_LPIET    GENMASK(19, 3)
#define MAC_1US_TIC_COUNTER               0xDC
#define MAC_1US_TIC_COUNTER_TIC_1US_CNTR  GENMASK(11, 0)
#define MAC_VERSION                       0x110
#define MAC_VERSION_SNPSVER               GENMASK(7, 0)
#define MAC_VERSION_DEVID                 GENMASK(15, 8)
#define MAC_VERSION_USERVER               GENMASK(23, 16)
#define MAC_DEBUG                         0x114
#define MAC_DEBUG_RPESTS                  BIT(0)
#define MAC_DEBUG_RFCFCSTS                GENMASK(2, 1)
#define MAC_DEBUG_TPESTS                  BIT(16)
#define MAC_DEBUG_TFCSTS                  GENMASK(18, 17)

#define MAC_HW_FEATURE0              0x11C
#define MAC_HW_FEATURE0_RGMIISEL     BIT(0)
#define MAC_HW_FEATURE0_GMIISEL      BIT(1)
#define MAC_HW_FEATURE0_RMIISEL      BIT(2)
#define MAC_HW_FEATURE0_HDSEL        BIT(3)
#define MAC_HW_FEATURE0_VLHASH       BIT(4)
#define MAC_HW_FEATURE0_SMASEL       BIT(5)
#define MAC_HW_FEATURE0_RWKSEL       BIT(6)
#define MAC_HW_FEATURE0_MGKSEL       BIT(7)
#define MAC_HW_FEATURE0_MMCSEL       BIT(8)
#define MAC_HW_FEATURE0_ARPOFFSEL    BIT(9)
#define MAC_HW_FEATURE0_RAVSEL       BIT(10)
#define MAC_HW_FEATURE0_AVSEL        BIT(11)
#define MAC_HW_FEATURE0_TSSEL        BIT(12)
#define MAC_HW_FEATURE0_EEESEL       BIT(13)
#define MAC_HW_FEATURE0_TXCOESEL     BIT(14)
#define MAC_HW_FEATURE0_RXCOESEL     BIT(16)
#define MAC_HW_FEATURE0_ADDMACADRSEL GENMASK(22, 18)
#define MAC_HW_FEATURE0_PHYSEL       GENMASK(24, 23)
#define MAC_HW_FEATURE0_TSSTSSEL     GENMASK(26, 25)
#define MAC_HW_FEATURE0_SAVLANINS    BIT(27)
#define MAC_HW_FEATURE0_VXN          BIT(29)
#define MAC_HW_FEATURE0_EDIFFC       BIT(30)
#define MAC_HW_FEATURE0_EDMA         BIT(31)

#define MAC_HW_FEATURE1            0x120
#define MAC_HW_FEATURE1_RXFIFOSIZE GENMASK(4, 0)
#define MAC_HW_FEATURE1_PFCEN      BIT(5)
#define MAC_HW_FEATURE1_TXFIFOSIZE GENMASK(10, 6)
#define MAC_HW_FEATURE1_OSTEN      BIT(11)
#define MAC_HW_FEATURE1_PTOEN      BIT(12)
#define MAC_HW_FEATURE1_ADVTHWORD  BIT(13)
#define MAC_HW_FEATURE1_ADDR64     GENMASK(15, 14)
#define MAC_HW_FEATURE1_DCBEN      BIT(16)
#define MAC_HW_FEATURE1_SPHEN      BIT(17)
#define MAC_HW_FEATURE1_TSOEN      BIT(18)
#define MAC_HW_FEATURE1_DBGMEMA    BIT(19)
#define MAC_HW_FEATURE1_RSSEN      BIT(20)
#define MAC_HW_FEATURE1_NUMTC      GENMASK(23, 21)
#define MAC_HW_FEATURE1_HASHTBLSZ  GENMASK(26, 24)
#define MAC_HW_FEATURE1_L3L4FNUM   GENMASK(30, 27)

#define MAC_HW_FEATURE2            0x124
#define MAC_HW_FEATURE2_RXQCNT     GENMASK(3, 0)
#define MAC_HW_FEATURE2_TXQCNT     GENMASK(9, 6)
#define MAC_HW_FEATURE2_RXCHCNT    GENMASK(15, 12)
#define MAC_HW_FEATURE2_TXCHCNT    GENMASK(21, 18)
#define MAC_HW_FEATURE2_PPSOUTNUM  GENMASK(26, 24)
#define MAC_HW_FEATURE2_AUXSNAPNUM GENMASK(30, 28)

#define MAC_HW_FEATURE3         0x128
#define MAC_HW_FEATURE3_NRVF    GENMASK(2, 0)
#define MAC_HW_FEATURE3_FRPSEL  BIT(3)
#define MAC_HW_FEATURE3_CBTISEL BIT(4)
#define MAC_HW_FEATURE3_FRPPIPE GENMASK(7, 5)
#define MAC_HW_FEATURE3_POUOST  BIT(8)
#define MAC_HW_FEATURE3_FRPPB   GENMASK(10, 9)
#define MAC_HW_FEATURE3_FRPES   GENMASK(12, 11)
#define MAC_HW_FEATURE3_DVLAN   BIT(13)
#define MAC_HW_FEATURE3_ASP     GENMASK(15, 14)
#define MAC_HW_FEATURE3_TTSFD   GENMASK(18, 16)
#define MAC_HW_FEATURE3_ESTSEL  BIT(19)
#define MAC_HW_FEATURE3_GCLDEP  GENMASK(22, 20)
#define MAC_HW_FEATURE3_GCLWID  GENMASK(24, 23)
#define MAC_HW_FEATURE3_SGFSEL  BIT(25)
#define MAC_HW_FEATURE3_FPESEL  BIT(26)
#define MAC_HW_FEATURE3_TBSSEL  BIT(27)
#define MAC_HW_FEATURE3_TBS_CH  GENMASK(31, 28)

#define MAC_HW_FEATURE4       0x12C
#define MAC_HW_FEATURE4_PCSEL GENMASK(1, 0)
#define MAC_HW_FEATURE4_EASP  BIT(4)
#define MAC_HW_FEATURE4_DSTS  BIT(8)

#define MAC_EXTENDED_CONFIGURATION                       0x140
#define MAC_EXTENDED_CONFIGURATION_EIPG                  GENMASK(6, 0)
#define MAC_EXTENDED_CONFIGURATION_DDS                   BIT(7)
#define MAC_EXTENDED_CONFIGURATION_TPRE                  BIT(9)
#define MAC_EXTENDED_CONFIGURATION_DC                    BIT(17)
#define MAC_EXTENDED_CONFIGURATION_BL                    GENMASK(19, 18)
#define MAC_EXTENDED_CONFIGURATION_DR                    BIT(20)
#define MAC_EXTENDED_CONFIGURATION_DCRS                  BIT(21)
#define MAC_EXTENDED_CONFIGURATION_DO                    BIT(22)
#define MAC_EXTENDED_CONFIGURATION_ECRSFD                BIT(23)
#define MAC_EXTENDED_CONFIGURATION_HD                    BIT(24)
#define MAC_EXT_CFG1                                     0x144
#define MAC_EXT_CFG1_SPLOFST                             GENMASK(6, 0)
#define MAC_EXT_CFG1_SPLM                                GENMASK(9, 8)
#define MAC_EXT_CFG1_SAVO                                GENMASK(22, 16)
#define MAC_EXT_CFG1_SAVE                                BIT(24)
#define MAC_DPP_FSM_INTERRUPT_STATUS                     0x150
#define MAC_DPP_FSM_INTERRUPT_STATUS_DPES                BIT(1)
#define MAC_DPP_FSM_INTERRUPT_STATUS_MTPES               BIT(4)
#define MAC_DPP_FSM_INTERRUPT_STATUS_MTBUPES             BIT(6)
#define MAC_DPP_FSM_INTERRUPT_STATUS_MTFCPES             BIT(7)
#define MAC_DPP_FSM_INTERRUPT_STATUS_ARPES               BIT(8)
#define MAC_DPP_FSM_INTERRUPT_STATUS_MRWCPES             BIT(9)
#define MAC_DPP_FSM_INTERRUPT_STATUS_MRRCPES             BIT(10)
#define MAC_DPP_FSM_INTERRUPT_STATUS_CWPES               BIT(11)
#define MAC_DPP_FSM_INTERRUPT_STATUS_ASRPES              BIT(12)
#define MAC_DPP_FSM_INTERRUPT_STATUS_TTES                BIT(13)
#define MAC_DPP_FSM_INTERRUPT_STATUS_RTES                BIT(14)
#define MAC_DPP_FSM_INTERRUPT_STATUS_ATES                BIT(16)
#define MAC_DPP_FSM_INTERRUPT_STATUS_PTES                BIT(17)
#define MAC_DPP_FSM_INTERRUPT_STATUS_MSTTES              BIT(21)
#define MAC_DPP_FSM_INTERRUPT_STATUS_SLVTES              BIT(22)
#define MAC_DPP_FSM_INTERRUPT_STATUS_ATITES              BIT(23)
#define MAC_DPP_FSM_INTERRUPT_STATUS_ARITES              BIT(24)
#define MAC_DPP_FSM_INTERRUPT_STATUS_FSMPES              BIT(25)
#define MAC_DPP_FSM_INTERRUPT_STATUS_CPI                 BIT(31)
#define MAC_AXI_SLV_DPE_ADDR_STATUS                      0x154
#define MAC_AXI_SLV_DPE_ADDR_STATUS_ASPEAS               GENMASK(13, 0)
#define MAC_FSM_CONTROL                                  0x158
#define MAC_FSM_CONTROL_TMOUTEN                          BIT(0)
#define MAC_FSM_CONTROL_PRTYEN                           BIT(1)
#define MAC_FSM_CONTROL_TTEIN                            BIT(8)
#define MAC_FSM_CONTROL_RTEIN                            BIT(9)
#define MAC_FSM_CONTROL_ATEIN                            BIT(11)
#define MAC_FSM_CONTROL_PTEIN                            BIT(12)
#define MAC_FSM_CONTROL_TPEIN                            BIT(16)
#define MAC_FSM_CONTROL_RPEIN                            BIT(17)
#define MAC_FSM_CONTROL_APEIN                            BIT(19)
#define MAC_FSM_CONTROL_PPEIN                            BIT(20)
#define MAC_FSM_CONTROL_TLGRNML                          BIT(24)
#define MAC_FSM_CONTROL_RLGRNML                          BIT(25)
#define MAC_FSM_CONTROL_ALGRNML                          BIT(27)
#define MAC_FSM_CONTROL_PLGRNML                          BIT(28)
#define MAC_FSM_ACT_TIMER                                0x15C
#define MAC_FSM_ACT_TIMER_TMR                            GENMASK(9, 0)
#define MAC_FSM_ACT_TIMER_NTMRMD                         GENMASK(19, 16)
#define MAC_FSM_ACT_TIMER_LTMRMD                         GENMASK(23, 20)
#define MAC_FSM_ACT_TIMER_CTMR                           GENMASK(30, 28)
#define SNPS_SCS_REG1                                    0x160
#define MAC_SCSR_CONTROL                                 0x164
#define MAC_SCSR_CONTROL_CPEN                            BIT(0)
#define MAC_SCSR_CONTROL_CEIN                            BIT(1)
#define MAC_SCSR_PARITY_STATUS                           0x168
#define MAC_SCSR_PARITY_STATUS_CADD                      GENMASK(13, 0)
#define MAC_SCSR_PARITY_ERR_COUNT                        0x16C
#define MAC_SCSR_PARITY_ERR_COUNT_ECCL                   GENMASK(9, 0)
#define MAC_SCSR_PARITY_ERR_COUNT_ECLL                   GENMASK(25, 16)
#define MAC_FLEX_HDR_CFG                                 0x194
#define MAC_FLEX_HDR_CFG_FHRX                            BIT(0)
#define MAC_FLEX_HDR_CFG_FHTX                            BIT(1)
#define MAC_FLEX_HDR_CFG_EFLL                            BIT(2)
#define MAC_FLEX_HDR_CFG_FHSP                            GENMASK(12, 8)
#define MAC_FLEX_HDR_CFG_FHL                             GENMASK(26, 24)
#define MAC_FLEX_HDR_LOW                                 0x198
#define MAC_FLEX_HDR_HIGH                                0x19C
#define MDIO_SINGLE_COMMAND_ADDRESS                      0x200
#define MDIO_SINGLE_COMMAND_ADDRESS_RA                   GENMASK(15, 0)
#define MDIO_SINGLE_COMMAND_ADDRESS_PA                   GENMASK(20, 16)
#define MDIO_SINGLE_COMMAND_ADDRESS_DA                   GENMASK(25, 21)
#define MDIO_SINGLE_COMMAND_CONTROL_DATA                 0x204
#define MDIO_SINGLE_COMMAND_CONTROL_DATA_SDATA           GENMASK(15, 0)
#define MDIO_SINGLE_COMMAND_CONTROL_DATA_CMD             GENMASK(17, 16)
#define MDIO_SINGLE_COMMAND_CONTROL_DATA_SAADR           BIT(18)
#define MDIO_SINGLE_COMMAND_CONTROL_DATA_CR              GENMASK(21, 19)
#define MDIO_SINGLE_COMMAND_CONTROL_DATA_SBUSY           BIT(22)
#define MDIO_SINGLE_COMMAND_CONTROL_DATA_PSE             BIT(30)
#define MDIO_SINGLE_COMMAND_CONTROL_DATA_CRS             BIT(31)
#define MDIO_CONTINUOUS_WRITE_ADDRESS                    0x208
#define MDIO_CONTINUOUS_WRITE_ADDRESS_CREGADDR           GENMASK(15, 0)
#define MDIO_CONTINUOUS_WRITE_ADDRESS_CADDR              GENMASK(20, 16)
#define MDIO_CONTINUOUS_WRITE_ADDRESS_CPRT               BIT(21)
#define MDIO_CONTINUOUS_WRITE_ADDRESS_CBUSY              BIT(22)
#define MDIO_CONTINUOUS_WRITE_DATA                       0x20C
#define MDIO_CONTINUOUS_WRITE_DATA_CDATA                 GENMASK(15, 0)
#define MDIO_CONTINUOUS_SCAN_PORT_ENABLE                 0x210
#define MDIO_INTERRUPT_STATUS                            0x214
#define MDIO_INTERRUPT_STATUS_PORTNX4P0CONINT            BIT(0)
#define MDIO_INTERRUPT_STATUS_PORTNX4P1CONINT            BIT(1)
#define MDIO_INTERRUPT_STATUS_PORTNX4P2CONINT            BIT(2)
#define MDIO_INTERRUPT_STATUS_PORTNX4P3CONINT            BIT(3)
#define MDIO_INTERRUPT_STATUS_PORTNX4P0LSINT             BIT(4)
#define MDIO_INTERRUPT_STATUS_PORTNX4P1LSINT             BIT(5)
#define MDIO_INTERRUPT_STATUS_PORTNX4P2LSINT             BIT(6)
#define MDIO_INTERRUPT_STATUS_PORTNX4P3LSINT             BIT(7)
#define MDIO_INTERRUPT_STATUS_PORTNX4P0ALINT             BIT(8)
#define MDIO_INTERRUPT_STATUS_PORTNX4P1ALINT             BIT(9)
#define MDIO_INTERRUPT_STATUS_PORTNX4P2ALINT             BIT(10)
#define MDIO_INTERRUPT_STATUS_PORTNX4P3ALINT             BIT(11)
#define MDIO_INTERRUPT_STATUS_SNGLCOMPINT                BIT(12)
#define MDIO_INTERRUPT_STATUS_CWCOMPINT                  BIT(13)
#define MDIO_INTERRUPT_ENABLE                            0x218
#define MDIO_INTERRUPT_ENABLE_PTRNX4P0CONIE              BIT(0)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P1CONIE              BIT(1)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P2CONIE              BIT(2)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P3CONIE              BIT(3)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P0LSIE               BIT(4)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P1LSIE               BIT(5)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P2LSIE               BIT(6)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P3LSIE               BIT(7)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P0ALIE               BIT(8)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P1ALIE               BIT(9)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P2ALIE               BIT(10)
#define MDIO_INTERRUPT_ENABLE_PTRNX4P3ALIE               BIT(11)
#define MDIO_INTERRUPT_ENABLE_SNGLCOMPIE                 BIT(12)
#define MDIO_INTERRUPT_ENABLE_CWCOMPIE                   BIT(13)
#define MDIO_PORT_CONNECT_DISCONNECT_STATUS              0x21C
#define MDIO_CLAUSE_22_PORT                              0x220
#define MDIO_PORT_NX4_INDIRECT_CONTROL                   0x224
#define MDIO_PORT_NX4_INDIRECT_CONTROL_PRS               GENMASK(2, 0)
#define MDIO_PORTNX4P0_DEVICE_IN_USE                     0x230
#define MDIO_PORTNX4P0_DEVICE_IN_USE_NX4P0PMDPMA         BIT(1)
#define MDIO_PORTNX4P0_DEVICE_IN_USE_NX4P0WIS            BIT(2)
#define MDIO_PORTNX4P0_DEVICE_IN_USE_NX4P0PCS            BIT(3)
#define MDIO_PORTNX4P0_DEVICE_IN_USE_NX4P0PHYXS          BIT(4)
#define MDIO_PORTNX4P0_DEVICE_IN_USE_NX4P0DTEXS          BIT(5)
#define MDIO_PORTNX4P0_DEVICE_IN_USE_NX4P0TC             BIT(6)
#define MDIO_PORTNX4P0_DEVICE_IN_USE_NX4P0VSD1           BIT(30)
#define MDIO_PORTNX4P0_DEVICE_IN_USE_NX4P0VSD2           BIT(31)
#define MDIO_PORTNX4P0_LINK_STATUS                       0x234
#define MDIO_PORTNX4P0_LINK_STATUS_NX4P0PMDPMALS         BIT(1)
#define MDIO_PORTNX4P0_LINK_STATUS_NX4P0WISLS            BIT(2)
#define MDIO_PORTNX4P0_LINK_STATUS_NX4P0PCSLS            BIT(3)
#define MDIO_PORTNX4P0_LINK_STATUS_NX4P0PHYXSLS          BIT(4)
#define MDIO_PORTNX4P0_LINK_STATUS_NX4P0DTEXSLS          BIT(5)
#define MDIO_PORTNX4P0_LINK_STATUS_NX4P0TCLS             BIT(6)
#define MDIO_PORTNX4P0_LINK_STATUS_NX4P0VSD1LS           BIT(30)
#define MDIO_PORTNX4P0_LINK_STATUS_NX4P0VSD2LS           BIT(31)
#define MDIO_PORTNX4P0_ALIVE_STATUS                      0x238
#define MDIO_PORTNX4P0_ALIVE_STATUS_NX4P0PMDPMALS        BIT(1)
#define MDIO_PORTNX4P0_ALIVE_STATUS_NX4P0WISLS           BIT(2)
#define MDIO_PORTNX4P0_ALIVE_STATUS_NX4P0PCSLS           BIT(3)
#define MDIO_PORTNX4P0_ALIVE_STATUS_NX4P0PHYXSLS         BIT(4)
#define MDIO_PORTNX4P0_ALIVE_STATUS_NX4P0DTEXSLS         BIT(5)
#define MDIO_PORTNX4P0_ALIVE_STATUS_NX4P0TCLS            BIT(6)
#define MDIO_PORTNX4P0_ALIVE_STATUS_NX4P0VSD1LS          BIT(30)
#define MDIO_PORTNX4P0_ALIVE_STATUS_NX4P0VSD2LS          BIT(31)
#define MDIO_PORTNX4P1_DEVICE_IN_USE                     0x240
#define MDIO_PORTNX4P1_DEVICE_IN_USE_NX4P1PMDPMA         BIT(1)
#define MDIO_PORTNX4P1_DEVICE_IN_USE_NX4P1WIS            BIT(2)
#define MDIO_PORTNX4P1_DEVICE_IN_USE_NX4P1PCS            BIT(3)
#define MDIO_PORTNX4P1_DEVICE_IN_USE_NX4P1PHYXS          BIT(4)
#define MDIO_PORTNX4P1_DEVICE_IN_USE_NX4P1DTEXS          BIT(5)
#define MDIO_PORTNX4P1_DEVICE_IN_USE_NX4P1TC             BIT(6)
#define MDIO_PORTNX4P1_DEVICE_IN_USE_NX4P1VSD1           BIT(30)
#define MDIO_PORTNX4P1_DEVICE_IN_USE_NX4P1VSD2           BIT(31)
#define MDIO_PORTNX4P1_LINK_STATUS                       0x244
#define MDIO_PORTNX4P1_LINK_STATUS_NX4P1PMDPMALS         BIT(1)
#define MDIO_PORTNX4P1_LINK_STATUS_NX4P1WISLS            BIT(2)
#define MDIO_PORTNX4P1_LINK_STATUS_NX4P1PCSLS            BIT(3)
#define MDIO_PORTNX4P1_LINK_STATUS_NX4P1PHYXSLS          BIT(4)
#define MDIO_PORTNX4P1_LINK_STATUS_NX4P1DTEXSLS          BIT(5)
#define MDIO_PORTNX4P1_LINK_STATUS_NX4P1TCLS             BIT(6)
#define MDIO_PORTNX4P1_LINK_STATUS_NX4P1VSD1LS           BIT(30)
#define MDIO_PORTNX4P1_LINK_STATUS_NX4P1VSD2LS           BIT(31)
#define MDIO_PORTNX4P1_ALIVE_STATUS                      0x248
#define MDIO_PORTNX4P1_ALIVE_STATUS_NX4P1PMDPMALS        BIT(1)
#define MDIO_PORTNX4P1_ALIVE_STATUS_NX4P1WISLS           BIT(2)
#define MDIO_PORTNX4P1_ALIVE_STATUS_NX4P1PCSLS           BIT(3)
#define MDIO_PORTNX4P1_ALIVE_STATUS_NX4P1PHYXSLS         BIT(4)
#define MDIO_PORTNX4P1_ALIVE_STATUS_NX4P1DTEXSLS         BIT(5)
#define MDIO_PORTNX4P1_ALIVE_STATUS_NX4P1TCLS            BIT(6)
#define MDIO_PORTNX4P1_ALIVE_STATUS_NX4P1VSD1LS          BIT(30)
#define MDIO_PORTNX4P1_ALIVE_STATUS_NX4P1VSD2LS          BIT(31)
#define MDIO_PORTNX4P2_DEVICE_IN_USE                     0x250
#define MDIO_PORTNX4P2_DEVICE_IN_USE_NX4P2PMDPMA         BIT(1)
#define MDIO_PORTNX4P2_DEVICE_IN_USE_NX4P2WIS            BIT(2)
#define MDIO_PORTNX4P2_DEVICE_IN_USE_NX4P2PCS            BIT(3)
#define MDIO_PORTNX4P2_DEVICE_IN_USE_NX4P2PHYXS          BIT(4)
#define MDIO_PORTNX4P2_DEVICE_IN_USE_NX4P2DTEXS          BIT(5)
#define MDIO_PORTNX4P2_DEVICE_IN_USE_NX4P2TC             BIT(6)
#define MDIO_PORTNX4P2_DEVICE_IN_USE_NX4P2VSD1           BIT(30)
#define MDIO_PORTNX4P2_DEVICE_IN_USE_NX4P2VSD2           BIT(31)
#define MDIO_PORTNX4P2_LINK_STATUS                       0x254
#define MDIO_PORTNX4P2_LINK_STATUS_NX4P2PMDPMALS         BIT(1)
#define MDIO_PORTNX4P2_LINK_STATUS_NX4P2WISLS            BIT(2)
#define MDIO_PORTNX4P2_LINK_STATUS_NX4P2PCSLS            BIT(3)
#define MDIO_PORTNX4P2_LINK_STATUS_NX4P2PHYXSLS          BIT(4)
#define MDIO_PORTNX4P2_LINK_STATUS_NX4P2DTEXSLS          BIT(5)
#define MDIO_PORTNX4P2_LINK_STATUS_NX4P2TCLS             BIT(6)
#define MDIO_PORTNX4P2_LINK_STATUS_NX4P2VSD1LS           BIT(30)
#define MDIO_PORTNX4P2_LINK_STATUS_NX4P2VSD2LS           BIT(31)
#define MDIO_PORTNX4P2_ALIVE_STATUS                      0x258
#define MDIO_PORTNX4P2_ALIVE_STATUS_NX4P2PMDPMALS        BIT(1)
#define MDIO_PORTNX4P2_ALIVE_STATUS_NX4P2WISLS           BIT(2)
#define MDIO_PORTNX4P2_ALIVE_STATUS_NX4P2PCSLS           BIT(3)
#define MDIO_PORTNX4P2_ALIVE_STATUS_NX4P2PHYXSLS         BIT(4)
#define MDIO_PORTNX4P2_ALIVE_STATUS_NX4P2DTEXSLS         BIT(5)
#define MDIO_PORTNX4P2_ALIVE_STATUS_NX4P2TCLS            BIT(6)
#define MDIO_PORTNX4P2_ALIVE_STATUS_NX4P2VSD1LS          BIT(30)
#define MDIO_PORTNX4P2_ALIVE_STATUS_NX4P2VSD2LS          BIT(31)
#define MDIO_PORTNX4P3_DEVICE_IN_USE                     0x260
#define MDIO_PORTNX4P3_DEVICE_IN_USE_NX4P3PMDPMA         BIT(1)
#define MDIO_PORTNX4P3_DEVICE_IN_USE_NX4P3WIS            BIT(2)
#define MDIO_PORTNX4P3_DEVICE_IN_USE_NX4P3PCS            BIT(3)
#define MDIO_PORTNX4P3_DEVICE_IN_USE_NX4P3PHYXS          BIT(4)
#define MDIO_PORTNX4P3_DEVICE_IN_USE_NX4P3DTEXS          BIT(5)
#define MDIO_PORTNX4P3_DEVICE_IN_USE_NX4P3TC             BIT(6)
#define MDIO_PORTNX4P3_DEVICE_IN_USE_NX4P3VSD1           BIT(30)
#define MDIO_PORTNX4P3_DEVICE_IN_USE_NX4P3VSD2           BIT(31)
#define MDIO_PORTNX4P3_LINK_STATUS                       0x264
#define MDIO_PORTNX4P3_LINK_STATUS_NX4P3PMDPMALS         BIT(1)
#define MDIO_PORTNX4P3_LINK_STATUS_NX4P3WISLS            BIT(2)
#define MDIO_PORTNX4P3_LINK_STATUS_NX4P3PCSLS            BIT(3)
#define MDIO_PORTNX4P3_LINK_STATUS_NX4P3PHYXSLS          BIT(4)
#define MDIO_PORTNX4P3_LINK_STATUS_NX4P3DTEXSLS          BIT(5)
#define MDIO_PORTNX4P3_LINK_STATUS_NX4P3TCLS             BIT(6)
#define MDIO_PORTNX4P3_LINK_STATUS_NX4P3VSD1LS           BIT(30)
#define MDIO_PORTNX4P3_LINK_STATUS_NX4P3VSD2LS           BIT(31)
#define MDIO_PORTNX4P3_ALIVE_STATUS                      0x268
#define MDIO_PORTNX4P3_ALIVE_STATUS_NX4P3PMDPMALS        BIT(1)
#define MDIO_PORTNX4P3_ALIVE_STATUS_NX4P3WISLS           BIT(2)
#define MDIO_PORTNX4P3_ALIVE_STATUS_NX4P3PCSLS           BIT(3)
#define MDIO_PORTNX4P3_ALIVE_STATUS_NX4P3PHYXSLS         BIT(4)
#define MDIO_PORTNX4P3_ALIVE_STATUS_NX4P3DTEXSLS         BIT(5)
#define MDIO_PORTNX4P3_ALIVE_STATUS_NX4P3TCLS            BIT(6)
#define MDIO_PORTNX4P3_ALIVE_STATUS_NX4P3VSD1LS          BIT(30)
#define MDIO_PORTNX4P3_ALIVE_STATUS_NX4P3VSD2LS          BIT(31)
#define MAC_FPE_CTRL_STS                                 0x280
#define MAC_FPE_CTRL_STS_EFPE                            BIT(0)
#define MAC_FPE_CTRL_STS_SVER                            BIT(1)
#define MAC_FPE_CTRL_STS_SRSP                            BIT(2)
#define MAC_FPE_CTRL_STS_ARV                             BIT(3)
#define MAC_FPE_CTRL_STS_RVER                            BIT(16)
#define MAC_FPE_CTRL_STS_RRSP                            BIT(17)
#define MAC_FPE_CTRL_STS_TVER                            BIT(18)
#define MAC_FPE_CTRL_STS_TRSP                            BIT(19)
#define MAC_CSR_SW_CTRL                                  0x290
#define MAC_CSR_SW_CTRL_RCWE                             BIT(0)
#define MAC_CSR_SW_CTRL_SEEN                             BIT(8)
#define MAC_ADDRESSX_HIGH(i)                             (0x300 + i * 0x8)
#define MAC_ADDRESS0_HIGH_ADDRHI                         GENMASK(15, 0)
#define MAC_ADDRESS0_HIGH_DCS                            GENMASK(18, 16)
#define MAC_ADDRESS0_HIGH_AE                             BIT(31)
#define MAC_ADDRESSX_LOW(i)                              (0x304 + i * 0x8)
#define MAC_ADDRESSX_HIGH_ADDRHI                         GENMASK(15, 0)
#define MAC_ADDRESSX_HIGH_DCS                            GENMASK(18, 16)
#define MAC_ADDRESSX_HIGH_MBC                            GENMASK(29, 24)
#define MAC_ADDRESSX_HIGH_SA                             BIT(30)
#define MAC_ADDRESSX_HIGH_AE                             BIT(31)
#define MAC_INDIR_ACCESS_CTRL                            0x700
#define MAC_INDIR_ACCESS_CTRL_OB                         BIT(0)
#define MAC_INDIR_ACCESS_CTRL_COM                        BIT(1)
#define MAC_INDIR_ACCESS_CTRL_AUTO                       BIT(5)
#define MAC_INDIR_ACCESS_CTRL_AOFF                       GENMASK(15, 8)
#define MAC_INDIR_ACCESS_CTRL_MSEL                       GENMASK(29, 26)
#define MAC_INDIR_ACCESS_CTRL_SNPS_R                     BIT(31)
#define MAC_INDIR_ACCESS_DATA                            0x704
#define MAC_PCTH_INTR_ENABLE                             0x708
#define MAC_PCTH_INTR_ENABLE_PCTIE                       GENMASK(15, 0)
#define MAC_PCTH_INTR_STATUS                             0x70C
#define MAC_PCTH_INTR_STATUS_PCTIS                       GENMASK(15, 0)
#define MAC_PCTW_INTR_ENABLE                             0x730
#define MAC_PCTW_INTR_ENABLE_TWIE                        GENMASK(3, 0)
#define MAC_PCTW_INTR_STATUS                             0x734
#define MAC_PCTW_INTR_STATUS_TWIS                        GENMASK(3, 0)
#define MMC_CONTROL                                      0x800
#define MMC_CONTROL_CNTRST                               BIT(0)
#define MMC_CONTROL_CNTSTOPRO                            BIT(1)
#define MMC_CONTROL_RSTONRD                              BIT(2)
#define MMC_CONTROL_MCF                                  BIT(3)
#define MMC_CONTROL_MCT                                  GENMASK(5, 4)
#define MMC_CONTROL_CNTPRST                              BIT(7)
#define MMC_RX_INTERRUPT                                 0x804
#define MMC_RX_INTERRUPT_RXGBPKTIS                       BIT(0)
#define MMC_RX_INTERRUPT_RXGBOCTIS                       BIT(1)
#define MMC_RX_INTERRUPT_RXGOCTIS                        BIT(2)
#define MMC_RX_INTERRUPT_RXBCGPIS                        BIT(3)
#define MMC_RX_INTERRUPT_RXMCGPIS                        BIT(4)
#define MMC_RX_INTERRUPT_RXCRCERPIS                      BIT(5)
#define MMC_RX_INTERRUPT_RXRUNTPIS                       BIT(6)
#define MMC_RX_INTERRUPT_RXJABERPIS                      BIT(7)
#define MMC_RX_INTERRUPT_RXUSIZEGPIS                     BIT(8)
#define MMC_RX_INTERRUPT_RXOSIZEGPIS                     BIT(9)
#define MMC_RX_INTERRUPT_RX64OCTGBPIS                    BIT(10)
#define MMC_RX_INTERRUPT_RX65T127OCTGBPIS                BIT(11)
#define MMC_RX_INTERRUPT_RX128T255OCTGBPIS               BIT(12)
#define MMC_RX_INTERRUPT_RX256T511OCTGBPIS               BIT(13)
#define MMC_RX_INTERRUPT_RX512T1023OCTGBPIS              BIT(14)
#define MMC_RX_INTERRUPT_RX1024TMAXOCTGBPIS              BIT(15)
#define MMC_RX_INTERRUPT_RXUCGPIS                        BIT(16)
#define MMC_RX_INTERRUPT_RXLENERPIS                      BIT(17)
#define MMC_RX_INTERRUPT_RXORANGEPIS                     BIT(18)
#define MMC_RX_INTERRUPT_RXPAUSPIS                       BIT(19)
#define MMC_RX_INTERRUPT_RXFOVPIS                        BIT(20)
#define MMC_RX_INTERRUPT_RXVLANGBPIS                     BIT(21)
#define MMC_RX_INTERRUPT_RXWDOGPIS                       BIT(22)
#define MMC_RX_INTERRUPT_RXDISPCGBIS                     BIT(23)
#define MMC_RX_INTERRUPT_RXDISOCGBIS                     BIT(24)
#define MMC_RX_INTERRUPT_RXLPIUSCIS                      BIT(25)
#define MMC_RX_INTERRUPT_RXLPITRCIS                      BIT(26)
#define MMC_RX_INTERRUPT_RXALEPIS                        BIT(27)
#define MMC_RX_INTERRUPT_SGPPIS                          BIT(28)
#define MMC_RX_INTERRUPT_SGFPIS                          BIT(29)
#define MMC_RX_INTERRUPT_RXPRMMCIS                       BIT(31)
#define MMC_TX_INTERRUPT                                 0x808
#define MMC_TX_INTERRUPT_TXGBOCTIS                       BIT(0)
#define MMC_TX_INTERRUPT_TXGBPKTIS                       BIT(1)
#define MMC_TX_INTERRUPT_TXBCGPIS                        BIT(2)
#define MMC_TX_INTERRUPT_TXMCGPIS                        BIT(3)
#define MMC_TX_INTERRUPT_TX64OCTGBPIS                    BIT(4)
#define MMC_TX_INTERRUPT_TX65T127OCTGBPIS                BIT(5)
#define MMC_TX_INTERRUPT_TX128T255OCTGBPIS               BIT(6)
#define MMC_TX_INTERRUPT_TX256T511OCTGBPIS               BIT(7)
#define MMC_TX_INTERRUPT_TX512T1023OCTGBPIS              BIT(8)
#define MMC_TX_INTERRUPT_TX1024TMAXOCTGBPIS              BIT(9)
#define MMC_TX_INTERRUPT_TXUCGBPIS                       BIT(10)
#define MMC_TX_INTERRUPT_TXMCGBPIS                       BIT(11)
#define MMC_TX_INTERRUPT_TXBCGBPIS                       BIT(12)
#define MMC_TX_INTERRUPT_TXUFLOWERPIS                    BIT(13)
#define MMC_TX_INTERRUPT_TXGOCTIS                        BIT(14)
#define MMC_TX_INTERRUPT_TXGPKTIS                        BIT(15)
#define MMC_TX_INTERRUPT_TXPAUSPIS                       BIT(16)
#define MMC_TX_INTERRUPT_TXVLANGPIS                      BIT(17)
#define MMC_TX_INTERRUPT_TXLPIUSCIS                      BIT(18)
#define MMC_TX_INTERRUPT_TXLPITRCIS                      BIT(19)
#define MMC_TX_INTERRUPT_TXSCOLGPIS                      BIT(20)
#define MMC_TX_INTERRUPT_TXMCOLGPIS                      BIT(21)
#define MMC_TX_INTERRUPT_TXDEFPIS                        BIT(22)
#define MMC_TX_INTERRUPT_TXLATCOLPIS                     BIT(23)
#define MMC_TX_INTERRUPT_TXEXCOLPIS                      BIT(24)
#define MMC_TX_INTERRUPT_TXCARERPIS                      BIT(25)
#define MMC_TX_INTERRUPT_TXEXDEFPIS                      BIT(26)
#define MMC_TX_INTERRUPT_TXPRMMCIS                       BIT(31)
#define MMC_RECEIVE_INTERRUPT_ENABLE                     0x80C
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXGBPKTIE           BIT(0)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXGBOCTIE           BIT(1)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXGOCTIE            BIT(2)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXBCGPIE            BIT(3)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXMCGPIE            BIT(4)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXCRCERPIE          BIT(5)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXRUNTPIE           BIT(6)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXJABERPIE          BIT(7)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXUSIZEGPIE         BIT(8)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXOSIZEGPIE         BIT(9)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RX64OCTGBPIE        BIT(10)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RX65T127OCTGBPIE    BIT(11)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RX128T255OCTGBPIE   BIT(12)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RX256T511OCTGBPIE   BIT(13)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RX512T1023OCTGBPIE  BIT(14)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RX1024TMAXOCTGBPIE  BIT(15)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXUCGPIE            BIT(16)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXLENERPIE          BIT(17)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXORANGEPIE         BIT(18)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXPAUSPIE           BIT(19)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXFOVPIE            BIT(20)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXVLANGBPIE         BIT(21)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXWDOGPIE           BIT(22)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXDISPCGBIE         BIT(23)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXDISOCGBIE         BIT(24)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXLPIUSCIE          BIT(25)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXLPITRCIE          BIT(26)
#define MMC_RECEIVE_INTERRUPT_ENABLE_RXALEPIE            BIT(27)
#define MMC_RECEIVE_INTERRUPT_ENABLE_SGPPIE              BIT(28)
#define MMC_RECEIVE_INTERRUPT_ENABLE_SGFPIE              BIT(29)
#define MMC_TRANSMIT_INTERRUPT_ENABLE                    0x810
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXGBOCTIE          BIT(0)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXGBPKTIE          BIT(1)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXBCGPIE           BIT(2)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXMCGPIE           BIT(3)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TX64OCTGBPIE       BIT(4)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TX65T127OCTGBPIE   BIT(5)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TX128T255OCTGBPIE  BIT(6)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TX256T511OCTGBPIE  BIT(7)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TX512T1023OCTGBPIE BIT(8)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TX1024TMAXOCTGBPIE BIT(9)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXUCGBPIE          BIT(10)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXMCGBPIE          BIT(11)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXBCGBPIE          BIT(12)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXUFLOWERPIE       BIT(13)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXGOCTIE           BIT(14)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXGPKTIE           BIT(15)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXPAUSPIE          BIT(16)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXVLANGPIE         BIT(17)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXLPIUSCIE         BIT(18)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXLPITRCIE         BIT(19)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXSCOLGPIE         BIT(20)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXMCOLGPIE         BIT(21)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXDEFPIE           BIT(22)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXLATCOLPIE        BIT(23)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXEXCOLPIE         BIT(24)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXCARERPIE         BIT(25)
#define MMC_TRANSMIT_INTERRUPT_ENABLE_TXEXDEFPIE         BIT(26)
#define TX_OCTET_COUNT_GOOD_BAD_LOW                      0x814
#define TX_OCTET_COUNT_GOOD_BAD_HIGH                     0x818
#define TX_PACKET_COUNT_GOOD_BAD_LOW                     0x81C
#define TX_BROADCAST_PACKETS_GOOD_LOW                    0x824
#define TX_MULTICAST_PACKETS_GOOD_LOW                    0x82C
#define TX_64OCTETS_PACKETS_GOOD_BAD_LOW                 0x834
#define TX_65TO127OCTETS_PACKETS_GOOD_BAD_LOW            0x83C
#define TX_128TO255OCTETS_PACKETS_GOOD_BAD_LOW           0x844
#define TX_256TO511OCTETS_PACKETS_GOOD_BAD_LOW           0x84C
#define TX_512TO1023OCTETS_PACKETS_GOOD_BAD_LOW          0x854
#define TX_1024TOMAXOCTETS_PACKETS_GOOD_BAD_LOW          0x85C
#define TX_UNICAST_PACKETS_GOOD_BAD_LOW                  0x864
#define TX_MULTICAST_PACKETS_GOOD_BAD_LOW                0x86C
#define TX_BROADCAST_PACKETS_GOOD_BAD_LOW                0x874
#define TX_UNDERFLOW_ERROR_PACKETS_LOW                   0x87C
#define TX_OCTET_COUNT_GOOD_LOW                          0x884
#define TX_OCTET_COUNT_GOOD_HIGH                         0x888
#define TX_PACKET_COUNT_GOOD_LOW                         0x88C
#define TX_PAUSE_PACKETS_LOW                             0x894
#define TX_VLAN_PACKETS_GOOD_LOW                         0x89C
#define TX_LPI_USEC_CNTR                                 0x8A4
#define TX_LPI_TRAN_CNTR                                 0x8A8
#define RX_PACKET_COUNT_GOOD_BAD_LOW                     0x900
#define RX_OCTET_COUNT_GOOD_BAD_LOW                      0x908
#define RX_OCTET_COUNT_GOOD_BAD_HIGH                     0x90C
#define RX_OCTET_COUNT_GOOD_LOW                          0x910
#define RX_OCTET_COUNT_GOOD_HIGH                         0x914
#define RX_BROADCAST_PACKETS_GOOD_LOW                    0x918
#define RX_MULTICAST_PACKETS_GOOD_LOW                    0x920
#define RX_CRC_ERROR_PACKETS_LOW                         0x928
#define RX_RUNT_ERROR_PACKETS                            0x930
#define RX_JABBER_ERROR_PACKETS                          0x934
#define RX_UNDERSIZE_PACKETS_GOOD                        0x938
#define RX_OVERSIZE_PACKETS_GOOD                         0x93C
#define RX_64OCTETS_PACKETS_GOOD_BAD_LOW                 0x940
#define RX_65TO127OCTETS_PACKETS_GOOD_BAD_LOW            0x948
#define RX_128TO255OCTETS_PACKETS_GOOD_BAD_LOW           0x950
#define RX_256TO511OCTETS_PACKETS_GOOD_BAD_LOW           0x958
#define RX_512TO1023OCTETS_PACKETS_GOOD_BAD_LOW          0x960
#define RX_1024TOMAXOCTETS_PACKETS_GOOD_BAD_LOW          0x968
#define RX_UNICAST_PACKETS_GOOD_LOW                      0x970
#define RX_LENGTH_ERROR_PACKETS_LOW                      0x978
#define RX_OUTOFRANGE_PACKETS_LOW                        0x980
#define RX_PAUSE_PACKETS_LOW                             0x988
#define RX_FIFOOVERFLOW_PACKETS_LOW                      0x990
#define RX_VLAN_PACKETS_GOOD_BAD_LOW                     0x998
#define RX_WATCHDOG_ERROR_PACKETS                        0x9A0
#define RX_LPI_USEC_CNTR                                 0x9A4
#define RX_LPI_TRAN_CNTR                                 0x9A8
#define RX_DISCARD_PACKETS_GOOD_BAD_LOW                  0x9AC
#define RX_DISCARD_OCTETS_GOOD_BAD_LOW                   0x9B4
#define RX_DISCARD_OCTETS_GOOD_BAD_HIGH                  0x9B8
#define RX_ALIGNMENT_ERROR_PACKETS                       0x9BC
#define SGF_PASS_PKTCNT                                  0x9F0
#define SGF_FAIL_PKTCNT                                  0x9F4
#define MMC_FPE_TX_INTERRUPT                             0xA00
#define MMC_FPE_TX_INTERRUPT_FCIS                        BIT(0)
#define MMC_FPE_TX_INTERRUPT_HRCIS                       BIT(1)
#define MMC_FPE_TX_INTERRUPT_GOCIS                       BIT(2)
#define MMC_FPE_TX_INTERRUPT_MASK                        0xA04
#define MMC_FPE_TX_INTERRUPT_MASK_FCIM                   BIT(0)
#define MMC_FPE_TX_INTERRUPT_MASK_HRCIM                  BIT(1)
#define MMC_FPE_TX_INTERRUPT_MASK_GOCIM                  BIT(2)
#define MMC_TX_FPE_FRAGMENT_CNTR                         0xA08
#define MMC_TX_HOLD_REQ_CNTR                             0xA0C
#define MMC_TX_GATE_ORUN_CNTR_LOW                        0xA10
#define MMC_TX_GATE_ORUN_CNTR_HIGH                       0xA14
#define MMC_FPE_RX_INTERRUPT                             0xA20
#define MMC_FPE_RX_INTERRUPT_PAECIS                      BIT(0)
#define MMC_FPE_RX_INTERRUPT_PSECIS                      BIT(1)
#define MMC_FPE_RX_INTERRUPT_PAOCIS                      BIT(2)
#define MMC_FPE_RX_INTERRUPT_FCIS                        BIT(3)
#define MMC_FPE_RX_INTERRUPT_MASK                        0xA24
#define MMC_FPE_RX_INTERRUPT_MASK_PAECIM                 BIT(0)
#define MMC_FPE_RX_INTERRUPT_MASK_PSECIM                 BIT(1)
#define MMC_FPE_RX_INTERRUPT_MASK_PAOCIM                 BIT(2)
#define MMC_FPE_RX_INTERRUPT_MASK_FCIM                   BIT(3)
#define MMC_RX_PACKET_ASSEMBLY_ERR_CNTR                  0xA28
#define MMC_RX_PACKET_SMD_ERR_CNTR                       0xA2C
#define MMC_RX_PACKET_ASSEMBLY_OK_CNTR                   0xA30
#define MMC_RX_FPE_FRAGMENT_CNTR                         0xA34
#define TX_SINGLE_COLLISION_GOOD_PACKETS                 0xA40
#define TX_MULTIPLE_COLLISION_GOOD_PACKETS               0xA44
#define TX_DEFERRED_PACKETS                              0xA48
#define TX_LATE_COLLISION_PACKETS                        0xA4C
#define TX_EXCESSIVE_COLLISION_PACKETS                   0xA50
#define TX_CARRIER_ERROR_PACKETS                         0xA54
#define TX_EXCESSIVE_DEFERRAL_ERROR                      0xA58
#define MMC_IPC_RX_INTERRUPT_MASK                        0xA5C
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4GPIM             BIT(0)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4HERPIM           BIT(1)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4NOPAYPIM         BIT(2)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4FRAGPIM          BIT(3)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4UDSBLPIM         BIT(4)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV6GPIM             BIT(5)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV6HERPIM           BIT(6)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV6NOPAYPIM         BIT(7)
#define MMC_IPC_RX_INTERRUPT_MASK_RXUDPGPIM              BIT(8)
#define MMC_IPC_RX_INTERRUPT_MASK_RXUDPERPIM             BIT(9)
#define MMC_IPC_RX_INTERRUPT_MASK_RXTCPGPIM              BIT(10)
#define MMC_IPC_RX_INTERRUPT_MASK_RXTCPERPIM             BIT(11)
#define MMC_IPC_RX_INTERRUPT_MASK_RXICMPGPIM             BIT(12)
#define MMC_IPC_RX_INTERRUPT_MASK_RXICMPERPIM            BIT(13)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4GOIM             BIT(16)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4HEROIM           BIT(17)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4NOPAYOIM         BIT(18)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4FRAGOIM          BIT(19)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV4UDSBLOIM         BIT(20)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV6GOIM             BIT(21)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV6HEROIM           BIT(22)
#define MMC_IPC_RX_INTERRUPT_MASK_RXIPV6NOPAYOIM         BIT(23)
#define MMC_IPC_RX_INTERRUPT_MASK_RXUDPGOIM              BIT(24)
#define MMC_IPC_RX_INTERRUPT_MASK_RXUDPEROIM             BIT(25)
#define MMC_IPC_RX_INTERRUPT_MASK_RXTCPGOIM              BIT(26)
#define MMC_IPC_RX_INTERRUPT_MASK_RXTCPEROIM             BIT(27)
#define MMC_IPC_RX_INTERRUPT_MASK_RXICMPGOIM             BIT(28)
#define MMC_IPC_RX_INTERRUPT_MASK_RXICMPEROIM            BIT(29)
#define MMC_IPC_RX_INTERRUPT                             0xA60
#define MMC_IPC_RX_INTERRUPT_RXIPV4GPIS                  BIT(0)
#define MMC_IPC_RX_INTERRUPT_RXIPV4HERPIS                BIT(1)
#define MMC_IPC_RX_INTERRUPT_RXIPV4NOPAYPIS              BIT(2)
#define MMC_IPC_RX_INTERRUPT_RXIPV4FRAGPIS               BIT(3)
#define MMC_IPC_RX_INTERRUPT_RXIPV4UDSBLPIS              BIT(4)
#define MMC_IPC_RX_INTERRUPT_RXIPV6GPIS                  BIT(5)
#define MMC_IPC_RX_INTERRUPT_RXIPV6HERPIS                BIT(6)
#define MMC_IPC_RX_INTERRUPT_RXIPV6NOPAYPIS              BIT(7)
#define MMC_IPC_RX_INTERRUPT_RXUDPGPIS                   BIT(8)
#define MMC_IPC_RX_INTERRUPT_RXUDPERPIS                  BIT(9)
#define MMC_IPC_RX_INTERRUPT_RXTCPGPIS                   BIT(10)
#define MMC_IPC_RX_INTERRUPT_RXTCPERPIS                  BIT(11)
#define MMC_IPC_RX_INTERRUPT_RXICMPGPIS                  BIT(12)
#define MMC_IPC_RX_INTERRUPT_RXICMPERPIS                 BIT(13)
#define MMC_IPC_RX_INTERRUPT_RXIPV4GOIS                  BIT(16)
#define MMC_IPC_RX_INTERRUPT_RXIPV4HEROIS                BIT(17)
#define MMC_IPC_RX_INTERRUPT_RXIPV4NOPAYOIS              BIT(18)
#define MMC_IPC_RX_INTERRUPT_RXIPV4FRAGOIS               BIT(19)
#define MMC_IPC_RX_INTERRUPT_RXIPV4UDSBLOIS              BIT(20)
#define MMC_IPC_RX_INTERRUPT_RXIPV6GOIS                  BIT(21)
#define MMC_IPC_RX_INTERRUPT_RXIPV6HEROIS                BIT(22)
#define MMC_IPC_RX_INTERRUPT_RXIPV6NOPAYOIS              BIT(23)
#define MMC_IPC_RX_INTERRUPT_RXUDPGOIS                   BIT(24)
#define MMC_IPC_RX_INTERRUPT_RXUDPEROIS                  BIT(25)
#define MMC_IPC_RX_INTERRUPT_RXTCPGOIS                   BIT(26)
#define MMC_IPC_RX_INTERRUPT_RXTCPEROIS                  BIT(27)
#define MMC_IPC_RX_INTERRUPT_RXICMPGOIS                  BIT(28)
#define MMC_IPC_RX_INTERRUPT_RXICMPEROIS                 BIT(29)
#define RXIPV4_GOOD_PACKETS_LOW                          0xA64
#define RXIPV4_HEADER_ERROR_PACKETS_LOW                  0xA6C
#define RXIPV4_NO_PAYLOAD_PACKETS_LOW                    0xA74
#define RXIPV4_FRAGMENTED_PACKETS_LOW                    0xA7C
#define RXIPV4_UDP_CHECKSUM_DISABLED_PACKETS_LOW         0xA84
#define RXIPV6_GOOD_PACKETS_LOW                          0xA8C
#define RXIPV6_HEADER_ERROR_PACKETS_LOW                  0xA94
#define RXIPV6_NO_PAYLOAD_PACKETS_LOW                    0xA9C
#define RXUDP_GOOD_PACKETS_LOW                           0xAA4
#define RXUDP_ERROR_PACKETS_LOW                          0xAAC
#define RXTCP_GOOD_PACKETS_LOW                           0xAB4
#define RXTCP_ERROR_PACKETS_LOW                          0xABC
#define RXICMP_GOOD_PACKETS_LOW                          0xAC4
#define RXICMP_ERROR_PACKETS_LOW                         0xACC
#define RXIPV4_GOOD_OCTETS_LOW                           0xAD4
#define RXIPV4_HEADER_ERROR_OCTETS_LOW                   0xADC
#define RXIPV4_NO_PAYLOAD_OCTETS_LOW                     0xAE4
#define RXIPV4_FRAGMENTED_OCTETS_LOW                     0xAEC
#define RXIPV4_UDP_CHECKSUM_DISABLE_OCTETS_LOW           0xAF4
#define RXIPV6_GOOD_OCTETS_LOW                           0xAFC
#define RXIPV6_HEADER_ERROR_OCTETS_LOW                   0xB04
#define RXIPV6_NO_PAYLOAD_OCTETS_LOW                     0xB0C
#define RXUDP_GOOD_OCTETS_LOW                            0xB14
#define RXUDP_ERROR_OCTETS_LOW                           0xB1C
#define RXTCP_GOOD_OCTETS_LOW                            0xB24
#define RXTCP_ERROR_OCTETS_LOW                           0xB2C
#define RXICMP_GOOD_OCTETS_LOW                           0xB34
#define RXICMP_ERROR_OCTETS_LOW                          0xB3C
#define MAC_L3_L4_ADDRESS_CONTROL                        0xC00
#define MAC_L3_L4_ADDRESS_CONTROL_XB                     BIT(0)
#define MAC_L3_L4_ADDRESS_CONTROL_TT                     BIT(1)
#define MAC_L3_L4_ADDRESS_CONTROL_IDDR                   GENMASK(14, 8)
#define MAC_L3_L4_DATA                                   0xC04
#define MAC_TIMESTAMP_CONTROL                            0xD00
#define MAC_TIMESTAMP_CONTROL_TSENA                      BIT(0)
#define MAC_TIMESTAMP_CONTROL_TSCFUPDT                   BIT(1)
#define MAC_TIMESTAMP_CONTROL_TSINIT                     BIT(2)
#define MAC_TIMESTAMP_CONTROL_TSUPDT                     BIT(3)
#define MAC_TIMESTAMP_CONTROL_TSADDREG                   BIT(5)
#define MAC_TIMESTAMP_CONTROL_PTGE                       BIT(6)
#define MAC_TIMESTAMP_CONTROL_TSENALL                    BIT(8)
#define MAC_TIMESTAMP_CONTROL_TSCTRLSSR                  BIT(9)
#define MAC_TIMESTAMP_CONTROL_TSVER2ENA                  BIT(10)
#define MAC_TIMESTAMP_CONTROL_TSIPENA                    BIT(11)
#define MAC_TIMESTAMP_CONTROL_TSIPV6ENA                  BIT(12)
#define MAC_TIMESTAMP_CONTROL_TSIPV4ENA                  BIT(13)
#define MAC_TIMESTAMP_CONTROL_TSEVNTENA                  BIT(14)
#define MAC_TIMESTAMP_CONTROL_TSMSTRENA                  BIT(15)
#define MAC_TIMESTAMP_CONTROL_SNAPTYPSEL                 GENMASK(17, 16)
#define MAC_TIMESTAMP_CONTROL_TSENMACADDR                BIT(18)
#define MAC_TIMESTAMP_CONTROL_CSC                        BIT(19)
#define MAC_TIMESTAMP_CONTROL_ESTI                       BIT(20)
#define MAC_TIMESTAMP_CONTROL_TXTSSTSM                   BIT(24)
#define MAC_TIMESTAMP_CONTROL_AV8021ASMEN                BIT(28)
#define MAC_SUB_SECOND_INCREMENT                         0xD04
#define MAC_SUB_SECOND_INCREMENT_SNSINC                  GENMASK(15, 8)
#define MAC_SUB_SECOND_INCREMENT_SSINC                   GENMASK(23, 16)
#define MAC_SYSTEM_TIME_SECONDS                          0xD08
#define MAC_SYSTEM_TIME_NANOSECONDS                      0xD0C
#define MAC_SYSTEM_TIME_NANOSECONDS_TSSS                 GENMASK(30, 0)
#define MAC_SYSTEM_TIME_SECONDS_UPDATE                   0xD10
#define MAC_SYSTEM_TIME_NANOSECONDS_UPDATE               0xD14
#define MAC_SYSTEM_TIME_NANOSECONDS_UPDATE_TSSS          GENMASK(30, 0)
#define MAC_SYSTEM_TIME_NANOSECONDS_UPDATE_ADDSUB        BIT(31)
#define MAC_TIMESTAMP_ADDEND                             0xD18
#define MAC_SYSTEM_TIME_HIGHER_WORD_SECONDS              0xD1C
#define MAC_SYSTEM_TIME_HIGHER_WORD_SECONDS_TSHWR        GENMASK(15, 0)
#define MAC_TIMESTAMP_STATUS                             0xD20
#define MAC_TIMESTAMP_STATUS_TSSOVF                      BIT(0)
#define MAC_TIMESTAMP_STATUS_TSTARGT0                    BIT(1)
#define MAC_TIMESTAMP_STATUS_AUXTSTRIG                   BIT(2)
#define MAC_TIMESTAMP_STATUS_TSTRGTERR0                  BIT(3)
#define MAC_TIMESTAMP_STATUS_TSTARGT1                    BIT(4)
#define MAC_TIMESTAMP_STATUS_TSTRGTERR1                  BIT(5)
#define MAC_TIMESTAMP_STATUS_TSTARGT2                    BIT(6)
#define MAC_TIMESTAMP_STATUS_TSTRGTERR2                  BIT(7)
#define MAC_TIMESTAMP_STATUS_TSTARGT3                    BIT(8)
#define MAC_TIMESTAMP_STATUS_TSTRGTERR3                  BIT(9)
#define MAC_TIMESTAMP_STATUS_TTSNS                       GENMASK(14, 10)
#define MAC_TIMESTAMP_STATUS_TXTSC                       BIT(15)
#define MAC_TIMESTAMP_STATUS_ATSSTN                      GENMASK(19, 16)
#define MAC_TIMESTAMP_STATUS_ATSSTM                      BIT(24)
#define MAC_TIMESTAMP_STATUS_ATSNS                       GENMASK(29, 25)
#define MAC_TIMESTAMP_STATUS_LTSSOVF                     BIT(31)
#define MAC_RX_DOMAIN_TIME_INCR                          0xD24
#define MAC_RX_DOMAIN_TIME_INCR_RXSNS                    GENMASK(15, 8)
#define MAC_RX_DOMAIN_TIME_INCR_RXNS                     GENMASK(31, 16)
#define MAC_TX_DOMAIN_TIME_INCR                          0xD28
#define MAC_TX_DOMAIN_TIME_INCR_TXSNS                    GENMASK(15, 8)
#define MAC_TX_DOMAIN_TIME_INCR_TXNS                     GENMASK(31, 16)
#define MAC_TX_TIMESTAMP_STATUS_NANOSECONDS              0xD30
#define MAC_TX_TIMESTAMP_STATUS_NANOSECONDS_TXTSSLO      GENMASK(30, 0)
#define MAC_TX_TIMESTAMP_STATUS_NANOSECONDS_TXTSSMIS     BIT(31)
#define MAC_TX_TIMESTAMP_STATUS_SECONDS                  0xD34
#define MAC_TX_TIMESTAMP_STATUS_PKTID                    0xD38
#define MAC_TX_TIMESTAMP_STATUS_PKTID_PKTID              GENMASK(9, 0)
#define MAC_AUXILIARY_CONTROL                            0xD40
#define MAC_AUXILIARY_CONTROL_ATSFC                      BIT(0)
#define MAC_AUXILIARY_CONTROL_ATSEN0                     BIT(4)
#define MAC_AUXILIARY_CONTROL_ATSEN1                     BIT(5)
#define MAC_AUXILIARY_CONTROL_ATSEN2                     BIT(6)
#define MAC_AUXILIARY_CONTROL_ATSEN3                     BIT(7)
#define MAC_AUXILIARY_TIMESTAMP_NANOSECONDS              0xD48
#define MAC_AUXILIARY_TIMESTAMP_NANOSECONDS_AUXTSLO      GENMASK(30, 0)
#define MAC_AUXILIARY_TIMESTAMP_SECONDS                  0xD4C
#define MAC_TIMESTAMP_INGRESS_ASYM_CORR                  0xD50
#define MAC_TIMESTAMP_EGRESS_ASYM_CORR                   0xD54
#define MAC_TIMESTAMP_INGRESS_CORR_NANOSECOND            0xD58
#define MAC_TIMESTAMP_INGRESS_CORR_SUBNANOSECOND         0xD5C
#define MAC_TIMESTAMP_INGRESS_CORR_SUBNANOSECOND_TSICSNS GENMASK(15, 8)
#define MAC_TIMESTAMP_EGRESS_CORR_NANOSECOND             0xD60
#define MAC_TIMESTAMP_EGRESS_CORR_SUBNANOSECOND          0xD64
#define MAC_TIMESTAMP_EGRESS_CORR_SUBNANOSECOND_TSECSNS  GENMASK(15, 8)
#define MAC_PPS_CONTROL                                  0xD70
#define MAC_PPS_CONTROL_PPSCTRL0_PPSCMD0                 GENMASK(3, 0)
#define MAC_PPS_CONTROL_PPSEN0                           BIT(4)
#define MAC_PPS_CONTROL_TRGTMODSEL0                      GENMASK(6, 5)
#define MAC_PPS_CONTROL_MCGREN0                          BIT(7)
#define MAC_PPS_CONTROL_PPSCMD1                          GENMASK(11, 8)
#define MAC_PPS_CONTROL_PPSEN1                           BIT(12)
#define MAC_PPS_CONTROL_TRGTMODSEL1                      GENMASK(14, 13)
#define MAC_PPS_CONTROL_MCGREN1                          BIT(15)
#define MAC_PPS_EXTND_CTRL                               0xD74
#define MAC_PPS_EXTND_CTRL_TIMESEL                       BIT(0)
#define MAC_PPS0_TARGET_TIME_SECONDS                     0xD80
#define MAC_PPS0_TARGET_TIME_NANOSECONDS                 0xD84
#define MAC_PPS0_TARGET_TIME_NANOSECONDS_TTSL0           GENMASK(30, 0)
#define MAC_PPS0_TARGET_TIME_NANOSECONDS_TRGTBUSY0       BIT(31)
#define MAC_PPS0_INTERVAL                                0xD88
#define MAC_PPS0_WIDTH                                   0xD8C
#define MAC_PPS1_TARGET_TIME_SECONDS                     0xD90
#define MAC_PPS1_TARGET_TIME_NANOSECONDS                 0xD94
#define MAC_PPS1_TARGET_TIME_NANOSECONDS_TTSL1           GENMASK(30, 0)
#define MAC_PPS1_TARGET_TIME_NANOSECONDS_TRGTBUSY1       BIT(31)
#define MAC_PPS1_INTERVAL                                0xD98
#define MAC_PPS1_WIDTH                                   0xD9C
#define MAC_PRESN_TIME_NS                                0xDE0
#define MAC_PRESN_TIME_UPDT                              0xDE4
#define MAC_LOCAL_TIMESTAMP_CONTROL                      0xE00
#define MAC_LOCAL_TIMESTAMP_CONTROL_LTSENA               BIT(0)
#define MAC_LOCAL_TIMESTAMP_CONTROL_LTSINIT              BIT(2)
#define MAC_LOCAL_TIMESTAMP_CONTROL_LTSUPDT              BIT(3)
#define MAC_LOCAL_TIMESTAMP_CONTROL_LTSCTRLSSR           BIT(9)
#define MAC_LOCAL_TIMESTAMP_CONTROL_LESTI                BIT(20)
#define MAC_LOCAL_SUB_SECOND_INCREMENT                   0xE04
#define MAC_LOCAL_SUB_SECOND_INCREMENT_LSNSINC           GENMASK(15, 8)
#define MAC_LOCAL_SUB_SECOND_INCREMENT_LSSINC            GENMASK(23, 16)
#define MAC_LOCAL_SYSTEM_TIME_SECONDS                    0xE08
#define MAC_LOCAL_SYSTEM_TIME_NANOSECONDS                0xE0C
#define MAC_LOCAL_SYSTEM_TIME_NANOSECONDS_LTSSS          GENMASK(30, 0)
#define MAC_LOCAL_SYSTEM_TIME_SECONDS_UPDATE             0xE10
#define MAC_LOCAL_SYSTEM_TIME_NANOSECONDS_UPDATE         0xE14
#define MAC_LOCAL_SYSTEM_TIME_NANOSECONDS_UPDATE_LTSSS   GENMASK(30, 0)
#define MAC_LOCAL_SYSTEM_TIME_NANOSECONDS_UPDATE_LADDSUB BIT(31)
#define MAC_LOCAL_SYSTEM_TIME_HIGHER_WORD_SECONDS        0xE1C
#define MAC_LOCAL_SYSTEM_TIME_HIGHER_WORD_SECONDS_LTSHWR GENMASK(15, 0)
#define MAC_DUAL_TS_SRC_CTRL                             0xE24
#define MAC_DUAL_TS_SRC_CTRL_TSSMS                       BIT(0)
#define MAC_DUAL_TS_SRC_CTRL_SCHSMS                      BIT(4)
#define MAC_DUAL_TS_SRC_CTRL_PPSSMS                      GENMASK(9, 8)
#define MAC_DUAL_TS_SRC_CTRL_AUXSMS                      GENMASK(19, 16)
#define MAC_LOCAL_PRESN_TIME_NS                          0xE30
#define MAC_LOCAL_PRESN_TIME_UPDT                        0xE34
#define MTL_OPERATION_MODE                               0x1000
#define MTL_OPERATION_MODE_RAA                           BIT(2)
#define MTL_OPERATION_MODE_ETSALG                        GENMASK(6, 5)
#define MTL_OPERATION_MODE_FRPE                          BIT(15)
#define MTL_DEBUG_CONTROL                                0x1008
#define MTL_DEBUG_CONTROL_FDBGEN                         BIT(0)
#define MTL_DEBUG_CONTROL_DBGMOD                         BIT(1)
#define MTL_DEBUG_CONTROL_BYTEEN                         GENMASK(3, 2)
#define MTL_DEBUG_CONTROL_PKTSTATE                       GENMASK(6, 5)
#define MTL_DEBUG_CONTROL_RSTALL                         BIT(8)
#define MTL_DEBUG_CONTROL_RSTSEL                         BIT(9)
#define MTL_DEBUG_CONTROL_FIFORDEN                       BIT(10)
#define MTL_DEBUG_CONTROL_FIFOWREN                       BIT(11)
#define MTL_DEBUG_CONTROL_FIFOSEL                        GENMASK(13, 12)
#define MTL_DEBUG_CONTROL_PKTIE                          BIT(14)
#define MTL_DEBUG_CONTROL_EIEE                           BIT(16)
#define MTL_DEBUG_CONTROL_EIAEE                          BIT(17)
#define MTL_DEBUG_CONTROL_EIEC                           BIT(18)
#define MTL_DEBUG_STATUS                                 0x100C
#define MTL_DEBUG_STATUS_FIFOBUSY                        BIT(0)
#define MTL_DEBUG_STATUS_PKTSTATE                        GENMASK(2, 1)
#define MTL_DEBUG_STATUS_BYTEEN                          GENMASK(4, 3)
#define MTL_DEBUG_STATUS_PKTI                            BIT(8)
#define MTL_DEBUG_STATUS_LOCR                            GENMASK(31, 16)
#define MTL_FIFO_DEBUG_DATA                              0x1010
#define MTL_INTERRUPT_STATUS                             0x1020
#define MTL_INTERRUPT_STATUS_Q0IS                        BIT(0)
#define MTL_INTERRUPT_STATUS_Q1IS                        BIT(1)
#define MTL_INTERRUPT_STATUS_Q2IS                        BIT(2)
#define MTL_INTERRUPT_STATUS_Q3IS                        BIT(3)
#define MTL_INTERRUPT_STATUS_Q4IS                        BIT(4)
#define MTL_INTERRUPT_STATUS_Q5IS                        BIT(5)
#define MTL_INTERRUPT_STATUS_Q6IS                        BIT(6)
#define MTL_INTERRUPT_STATUS_Q7IS                        BIT(7)
#define MTL_INTERRUPT_STATUS_MACIS                       BIT(16)
#define MTL_INTERRUPT_STATUS_DBGIS                       BIT(17)
#define MTL_INTERRUPT_STATUS_ESTIS                       BIT(18)
#define MTL_INTERRUPT_STATUS_TINS                        BIT(19)
#define MTL_INTERRUPT_STATUS_SGFIS                       BIT(20)
#define MTL_INTERRUPT_STATUS_MTLPIS                      BIT(23)
#define MTL_RXQ_DMA_MAP0                                 0x1030
#define MTL_RXQ_DMA_MAP0_Q0MDMACH                        GENMASK(2, 0)
#define MTL_RXQ_DMA_MAP0_Q0DDMACH                        BIT(7)
#define MTL_RXQ_DMA_MAP0_Q1MDMACH                        GENMASK(10, 8)
#define MTL_RXQ_DMA_MAP0_Q1DDMACH                        BIT(15)
#define MTL_RXQ_DMA_MAP0_Q2MDMACH                        GENMASK(18, 16)
#define MTL_RXQ_DMA_MAP0_Q2DDMACH                        BIT(23)
#define MTL_RXQ_DMA_MAP0_Q3MDMACH                        GENMASK(26, 24)
#define MTL_RXQ_DMA_MAP0_Q3DDMACH                        BIT(31)
#define MTL_RXQ_DMA_MAP1                                 0x1034
#define MTL_RXQ_DMA_MAP1_Q4MDMACH                        GENMASK(2, 0)
#define MTL_RXQ_DMA_MAP1_Q4DDMACH                        BIT(7)
#define MTL_RXQ_DMA_MAP1_Q5MDMACH                        GENMASK(10, 8)
#define MTL_RXQ_DMA_MAP1_Q5DDMACH                        BIT(15)
#define MTL_RXQ_DMA_MAP1_Q6MDMACH                        GENMASK(18, 16)
#define MTL_RXQ_DMA_MAP1_Q6DDMACH                        BIT(23)
#define MTL_RXQ_DMA_MAP1_Q7MDMACH                        GENMASK(26, 24)
#define MTL_RXQ_DMA_MAP1_Q7DDMACH                        BIT(31)
#define MTL_TBS_CTRL                                     0x1048
#define MTL_TBS_CTRL_ESTM                                BIT(0)
#define MTL_TBS_CTRL_LEOV                                BIT(1)
#define MTL_TBS_CTRL_TIEN                                BIT(2)
#define MTL_TBS_CTRL_LEGOS                               GENMASK(6, 4)
#define MTL_TBS_CTRL_LEOS                                GENMASK(31, 8)
#define MTL_TBS_STATS                                    0x104C
#define MTL_TBS_STATS_EDQN                               GENMASK(7, 0)
#define MTL_EST_CONTROL                                  0x1050
#define MTL_EST_CONTROL_EEST                             BIT(0)
#define MTL_EST_CONTROL_SSWL                             BIT(1)
#define MTL_EST_CONTROL_QHLBF                            BIT(3)
#define MTL_EST_CONTROL_DDBF                             BIT(4)
#define MTL_EST_CONTROL_DFBS                             BIT(5)
#define MTL_EST_CONTROL_LCSE                             GENMASK(7, 6)
#define MTL_EST_CONTROL_TILS                             GENMASK(10, 8)
#define MTL_EST_CONTROL_CTOV                             GENMASK(22, 11)
#define MTL_EST_CONTROL_PTOV                             GENMASK(31, 23)
#define MTL_EST_OVERHEAD                                 0x1054
#define MTL_EST_OVERHEAD_OVHD                            GENMASK(7, 0)
#define MTL_EST_OVERHEAD_ABYT                            GENMASK(20, 16)
#define MTL_EST_STATUS                                   0x1058
#define MTL_EST_STATUS_SWLC                              BIT(0)
#define MTL_EST_STATUS_BTRE                              BIT(1)
#define MTL_EST_STATUS_HLBF                              BIT(2)
#define MTL_EST_STATUS_HLBS                              BIT(3)
#define MTL_EST_STATUS_CGCE                              BIT(4)
#define MTL_EST_STATUS_SWOL                              BIT(7)
#define MTL_EST_STATUS_BTRL                              GENMASK(15, 8)
#define MTL_EST_STATUS_CGSN                              GENMASK(19, 16)
#define MTL_EST_SCH_ERROR                                0x1060
#define MTL_EST_SCH_ERROR_SETN                           GENMASK(7, 0)
#define MTL_EST_FRM_SIZE_ERROR                           0x1064
#define MTL_EST_FRM_SIZE_ERROR_FETN                      GENMASK(7, 0)
#define MTL_EST_FRM_SIZE_CAPTURE                         0x1068
#define MTL_EST_FRM_SIZE_CAPTURE_HBFS                    GENMASK(14, 0)
#define MTL_EST_FRM_SIZE_CAPTURE_HBFQ                    GENMASK(18, 16)
#define MTL_EST_INTR_ENABLE                              0x1070
#define MTL_EST_INTR_ENABLE_IECC                         BIT(0)
#define MTL_EST_INTR_ENABLE_IEBE                         BIT(1)
#define MTL_EST_INTR_ENABLE_IEHF                         BIT(2)
#define MTL_EST_INTR_ENABLE_IEHS                         BIT(3)
#define MTL_EST_INTR_ENABLE_CGCE                         BIT(4)
#define MTL_GCL_CONTROL                                  0x1080
#define MTL_GCL_CONTROL_SRWO                             BIT(0)
#define MTL_GCL_CONTROL_R1W0                             BIT(1)
#define MTL_GCL_CONTROL_GCRR                             BIT(2)
#define MTL_GCL_CONTROL_GCLS                             BIT(3)
#define MTL_GCL_CONTROL_DBGM                             BIT(4)
#define MTL_GCL_CONTROL_DBGB                             BIT(5)
#define MTL_GCL_CONTROL_ADDR                             GENMASK(15, 8)
#define MTL_GCL_CONTROL_GCLEIEE                          BIT(21)
#define MTL_GCL_CONTROL_GCLEIAEE                         BIT(22)
#define MTL_GCL_CONTROL_GCLEIEC                          BIT(23)
#define MTL_GCL_DATA                                     0x1084
#define MTL_FPE_CTRL_STS                                 0x1090
#define MTL_FPE_CTRL_STS_AFSZ                            GENMASK(1, 0)
#define MTL_FPE_CTRL_STS_LBHT                            BIT(7)
#define MTL_FPE_CTRL_STS_PEC                             GENMASK(15, 8)
#define MTL_FPE_CTRL_STS_PHRSC                           BIT(16)
#define MTL_FPE_CTRL_STS_HRS                             BIT(28)
#define MTL_FPE_ADVANCE                                  0x1094
#define MTL_FPE_ADVANCE_HADV                             GENMASK(15, 0)
#define MTL_FPE_ADVANCE_RADV                             GENMASK(31, 16)
#define MTL_RXP_CONTROL_STATUS                           0x10A0
#define MTL_RXP_CONTROL_STATUS_NVE                       GENMASK(7, 0)
#define MTL_RXP_CONTROL_STATUS_FPE_RCH                   GENMASK(14, 12)
#define MTL_RXP_CONTROL_STATUS_NPE                       GENMASK(23, 16)
#define MTL_RXP_CONTROL_STATUS_SNPS_RSVD                 GENMASK(27, 25)
#define MTL_RXP_CONTROL_STATUS_PIPE                      GENMASK(30, 28)
#define MTL_RXP_CONTROL_STATUS_RXPI                      BIT(31)
#define MTL_RXP_INTERRUPT_CONTROL_STATUS                 0x10A4
#define MTL_RXP_INTERRUPT_CONTROL_STATUS_NVEOVIS         BIT(0)
#define MTL_RXP_INTERRUPT_CONTROL_STATUS_NPEOVIS         BIT(1)
#define MTL_RXP_INTERRUPT_CONTROL_STATUS_FOOVIS          BIT(2)
#define MTL_RXP_INTERRUPT_CONTROL_STATUS_PDRFIS          BIT(3)
#define MTL_RXP_INTERRUPT_CONTROL_STATUS_NVEOVIE         BIT(16)
#define MTL_RXP_INTERRUPT_CONTROL_STATUS_NPEOVIE         BIT(17)
#define MTL_RXP_INTERRUPT_CONTROL_STATUS_FOOVIE          BIT(18)
#define MTL_RXP_INTERRUPT_CONTROL_STATUS_PDRFIE          BIT(19)
#define MTL_INDIRECT_ACC_CONTROL_STATUS                  0x10B0
#define MTL_INDIRECT_ACC_CONTROL_STATUS_ADDR             GENMASK(9, 0)
#define MTL_INDIRECT_ACC_CONTROL_STATUS_WRRDN            BIT(16)
#define MTL_INDIRECT_ACC_CONTROL_STATUS_CRWSEL           BIT(17)
#define MTL_INDIRECT_ACC_CONTROL_STATUS_CRWEN            BIT(18)
#define MTL_INDIRECT_ACC_CONTROL_STATUS_RXPEIEE          BIT(20)
#define MTL_INDIRECT_ACC_CONTROL_STATUS_RXPEIEC          GENMASK(22, 21)
#define MTL_INDIRECT_ACC_CONTROL_STATUS_ACCSEL           GENMASK(25, 24)
#define MTL_INDIRECT_ACC_CONTROL_STATUS_STARTBUSY        BIT(31)
#define MTL_INDIRECT_ACC_DATA                            0x10B4
#define MTL_ECC_CONTROL                                  0x10C0
#define MTL_ECC_CONTROL_MTXED                            BIT(0)
#define MTL_ECC_CONTROL_MRXED                            BIT(1)
#define MTL_ECC_CONTROL_MGCLED                           BIT(2)
#define MTL_ECC_CONTROL_MRXPED                           BIT(3)
#define MTL_ECC_CONTROL_DESCED                           BIT(5)
#define MTL_ECC_CONTROL_MEEAO                            BIT(8)
#define MTL_SAFETY_INTERRUPT_STATUS                      0x10C4
#define MTL_SAFETY_INTERRUPT_STATUS_MECIS                BIT(0)
#define MTL_SAFETY_INTERRUPT_STATUS_MEUIS                BIT(1)
#define MTL_SAFETY_INTERRUPT_STATUS_MCSIS                BIT(31)
#define MTL_ECC_INTERRUPT_ENABLE                         0x10C8
#define MTL_ECC_INTERRUPT_ENABLE_TXCEIE                  BIT(0)
#define MTL_ECC_INTERRUPT_ENABLE_RXCEIE                  BIT(4)
#define MTL_ECC_INTERRUPT_ENABLE_GCEIE                   BIT(8)
#define MTL_ECC_INTERRUPT_ENABLE_RPCEIE                  BIT(12)
#define MTL_ECC_INTERRUPT_STATUS                         0x10CC
#define MTL_ECC_INTERRUPT_STATUS_TXCES                   BIT(0)
#define MTL_ECC_INTERRUPT_STATUS_TXAMS                   BIT(1)
#define MTL_ECC_INTERRUPT_STATUS_TXUES                   BIT(2)
#define MTL_ECC_INTERRUPT_STATUS_RXCES                   BIT(4)
#define MTL_ECC_INTERRUPT_STATUS_RXAMS                   BIT(5)
#define MTL_ECC_INTERRUPT_STATUS_RXUES                   BIT(6)
#define MTL_ECC_INTERRUPT_STATUS_GCES                    BIT(8)
#define MTL_ECC_INTERRUPT_STATUS_GAMS                    BIT(9)
#define MTL_ECC_INTERRUPT_STATUS_GUES                    BIT(10)
#define MTL_ECC_INTERRUPT_STATUS_RPCES                   BIT(12)
#define MTL_ECC_INTERRUPT_STATUS_RPAMS                   BIT(13)
#define MTL_ECC_INTERRUPT_STATUS_RPUES                   BIT(14)
#define MTL_ECC_INTERRUPT_STATUS_SCES                    BIT(16)
#define MTL_ECC_INTERRUPT_STATUS_SAMS                    BIT(17)
#define MTL_ECC_INTERRUPT_STATUS_SUES                    BIT(18)
#define MTL_ECC_ERR_STS_RCTL                             0x10D0
#define MTL_ECC_ERR_STS_RCTL_EESRE                       BIT(0)
#define MTL_ECC_ERR_STS_RCTL_EMS                         GENMASK(3, 1)
#define MTL_ECC_ERR_STS_RCTL_CCES                        BIT(4)
#define MTL_ECC_ERR_STS_RCTL_CUES                        BIT(5)
#define MTL_ECC_ERR_ADDR_STATUS                          0x10D4
#define MTL_ECC_ERR_ADDR_STATUS_ECEAS                    GENMASK(15, 0)
#define MTL_ECC_ERR_ADDR_STATUS_EUEAS                    GENMASK(31, 16)
#define MTL_ECC_ERR_CNTR_STATUS                          0x10D8
#define MTL_ECC_ERR_CNTR_STATUS_ECECS                    GENMASK(7, 0)
#define MTL_ECC_ERR_CNTR_STATUS_EUECS                    GENMASK(19, 16)
#define MTL_DPP_CONTROL                                  0x10E0
#define MTL_DPP_CONTROL_DDPP                             BIT(0)
#define MTL_DPP_CONTROL_OPE                              BIT(1)
#define MTL_DPP_CONTROL_IPEDC                            BIT(5)
#define MTL_DPP_CONTROL_IPEMTD                           BIT(8)
#define MTL_DPP_CONTROL_IPEMTBU                          BIT(10)
#define MTL_DPP_CONTROL_IPEMTFC                          BIT(11)
#define MTL_DPP_CONTROL_IPEAR                            BIT(12)
#define MTL_DPP_CONTROL_IPEMRWC                          BIT(13)
#define MTL_DPP_CONTROL_IPEMRRC                          BIT(14)
#define MTL_DPP_CONTROL_IPECW                            BIT(15)
#define MTL_DPP_CONTROL_IPEASR                           BIT(16)
#define MTL_DPP_ECC_EIC                                  0x10E4
#define MTL_DPP_ECC_EIC_BLEI                             GENMASK(7, 0)
#define MTL_DPP_ECC_EIC_EIM                              BIT(16)
#define MTL_SGF_CONTROL                                  0x10E8
#define MTL_SGF_CONTROL_ESGF                             BIT(0)
#define MTL_SGF_CONTROL_SSWL                             BIT(1)
#define MTL_SGF_CONTROL_SCTOV                            BIT(2)
#define MTL_SGF_CONTROL_TILS                             GENMASK(10, 8)
#define MTL_SGF_CONTROL_CTOV                             GENMASK(22, 11)
#define MTL_SGF_CONTROL_PTOV                             GENMASK(31, 23)
#define MTL_SGF_EXTENDED_CONTROL                         0x10EC
#define MTL_SGF_EXTENDED_CONTROL_FFPFF                   BIT(0)
#define MTL_SGF_EXTENDED_CONTROL_ESPF                    BIT(1)
#define MTL_SGF_STATUS                                   0x10F0
#define MTL_SGF_STATUS_SWLC                              BIT(0)
#define MTL_SGF_STATUS_BTRE                              BIT(1)
#define MTL_SGF_STATUS_CGCE                              BIT(4)
#define MTL_SGF_STATUS_SWOL                              BIT(7)
#define MTL_SGF_STATUS_BTRL                              GENMASK(15, 8)
#define MTL_SGF_INTERRUPT_ENABLE                         0x10F4
#define MTL_SGF_INTERRUPT_ENABLE_IECC                    BIT(0)
#define MTL_SGF_INTERRUPT_ENABLE_IEBE                    BIT(1)
#define MTL_SGF_INTERRUPT_ENABLE_CGCE                    BIT(4)
#define MTL_TXQX_OPERATION_MODE(i)                       (0x1100 + i * 0x80)
#define MTL_TXQX_OPERATION_MODE_FTQ                      BIT(0)
#define MTL_TXQX_OPERATION_MODE_TSF                      BIT(1)
#define MTL_TXQX_OPERATION_MODE_TXQEN                    GENMASK(3, 2)
#define MTL_TXQX_OPERATION_MODE_TTC                      GENMASK(6, 4)
#define MTL_TXQX_OPERATION_MODE_Q2TCMAP                  GENMASK(10, 8)
#define MTL_TXQX_OPERATION_MODE_TQS                      GENMASK(22, 16)
#define MTL_TXQX_UNDERFLOW(i)                            (0x1104 + i * 0x80)
#define MTL_TXQX_UNDERFLOW_UFPKTCNT                      GENMASK(10, 0)
#define MTL_TXQX_UNDERFLOW_UFCNTOVF                      BIT(15)
#define MTL_TXQX_DEBUG(i)                                (0x1108 + i * 0x80)
#define MTL_TXQX_DEBUG_TCPAUSED                          BIT(0)
#define MTL_TXQX_DEBUG_TRCSTS                            GENMASK(2, 1)
#define MTL_TXQX_DEBUG_TWCSTS                            BIT(3)
#define MTL_TXQX_DEBUG_TXQSTS                            BIT(4)
#define MTL_TXQX_DEBUG_TRCPSTS                           BIT(5)
#define MTL_TCX_ETS_CONTROL(i)                           (0x1110 + i * 0x80)
#define MTL_TCX_ETS_CONTROL_TSA                          GENMASK(1, 0)
#define MTL_TCX_ETS_CONTROL_CBSEN                        BIT(2)
#define MTL_TCX_QUANTUM_WEIGHT(i)                        (0x1118 + i * 0x80)
#define MTL_TCX_QUANTUM_WEIGHT_QW                        GENMASK(20, 0)
#define MTL_RXQX_OPERATION_MODE(i)                       (0x1140 + i * 0x80)
#define MTL_RXQX_OPERATION_MODE_RTC                      GENMASK(1, 0)
#define MTL_RXQX_OPERATION_MODE_FUF                      BIT(3)
#define MTL_RXQX_OPERATION_MODE_FEF                      BIT(4)
#define MTL_RXQX_OPERATION_MODE_RSF                      BIT(5)
#define MTL_RXQX_OPERATION_MODE_DIS_TCP_EF               BIT(6)
#define MTL_RXQX_OPERATION_MODE_EHFC                     BIT(7)
#define MTL_RXQX_OPERATION_MODE_RQS                      GENMASK(22, 16)
#define MTL_RXQX_MISSED_PKT_OVERFLOW_CNT(i)              (0x1144 + i * 0x80)
#define MTL_RXQX_MISSED_PKT_OVERFLOW_CNT_OVFPKTCNT       GENMASK(10, 0)
#define MTL_RXQX_MISSED_PKT_OVERFLOW_CNT_OVFCNTOVF       BIT(15)
#define MTL_RXQX_MISSED_PKT_OVERFLOW_CNT_MISPKTCNT       GENMASK(26, 16)
#define MTL_RXQX_MISSED_PKT_OVERFLOW_CNT_MISCNTOVF       BIT(31)
#define MTL_RXQX_DEBUG(i)                                (0x1148 + i * 0x80)
#define MTL_RXQX_DEBUG_RWCSTS                            BIT(0)
#define MTL_RXQX_DEBUG_RRCSTS                            GENMASK(2, 1)
#define MTL_RXQX_DEBUG_RXQSTS                            GENMASK(5, 4)
#define MTL_RXQX_DEBUG_PRXQ                              GENMASK(29, 16)
#define MTL_RXQX_CONTROL(i)                              (0x114C + i * 0x80)
#define MTL_RXQX_CONTROL_RXQ_WEGT                        GENMASK(2, 0)
#define MTL_RXQX_CONTROL_RXQ_PKT_ARBIT                   BIT(3)
#define MTL_RXQX_FLOW_CONTROL(i)                         (0x1150 + i * 0x80)
#define MTL_RXQX_FLOW_CONTROL_RFA                        GENMASK(6, 1)
#define MTL_RXQX_FLOW_CONTROL_RFD                        GENMASK(22, 17)
#define MTL_QX_INTERRUPT_ENABLE(i)                       (0x1170 + i * 0x80)
#define MTL_QX_INTERRUPT_ENABLE_TXUIE                    BIT(0)
#define MTL_QX_INTERRUPT_ENABLE_ABPSIE                   BIT(1)
#define MTL_QX_INTERRUPT_ENABLE_RXOIE                    BIT(16)
#define MTL_QX_INTERRUPT_STATUS(i)                       (0x1174 + i * 0x80)
#define MTL_QX_INTERRUPT_STATUS_TXUNFIS                  BIT(0)
#define MTL_QX_INTERRUPT_STATUS_ABPSIS                   BIT(1)
#define MTL_QX_INTERRUPT_STATUS_RXOVFIS                  BIT(16)
#define DMA_MODE                                         0x3000
#define DMA_MODE_SWR                                     BIT(0)
#define DMA_MODE_TDRP                                    BIT(4)
#define DMA_MODE_TMRP                                    BIT(5)
#define DMA_MODE_DSPW                                    BIT(8)
#define DMA_MODE_INTM                                    GENMASK(13, 12)
#define DMA_SYSBUS_MODE                                  0x3004
#define DMA_SYSBUS_MODE_UBL                              BIT(0)
#define DMA_SYSBUS_MODE_BLEN4                            BIT(1)
#define DMA_SYSBUS_MODE_BLEN8                            BIT(2)
#define DMA_SYSBUS_MODE_BLEN16                           BIT(3)
#define DMA_SYSBUS_MODE_BLEN32                           BIT(4)
#define DMA_SYSBUS_MODE_BLEN64                           BIT(5)
#define DMA_SYSBUS_MODE_BLEN128                          BIT(6)
#define DMA_SYSBUS_MODE_BLEN256                          BIT(7)
#define DMA_SYSBUS_MODE_AALE                             BIT(10)
#define DMA_SYSBUS_MODE_EAME                             BIT(11)
#define DMA_SYSBUS_MODE_AAL                              BIT(12)
#define DMA_SYSBUS_MODE_ONEKBBE                          BIT(13)
#define DMA_SYSBUS_MODE_LPI_XIT_PKT                      BIT(14)
#define DMA_SYSBUS_MODE_EN_LPI                           BIT(15)
#define DMA_SYSBUS_MODE_RD_OSR_LMT                       GENMASK(20, 16)
#define DMA_SYSBUS_MODE_WR_OSR_LMT                       GENMASK(28, 24)
#define DMA_INTERRUPT_STATUS                             0x3008
#define DMA_INTERRUPT_STATUS_DC0IS                       BIT(0)
#define DMA_INTERRUPT_STATUS_DC1IS                       BIT(1)
#define DMA_INTERRUPT_STATUS_DC2IS                       BIT(2)
#define DMA_INTERRUPT_STATUS_DC3IS                       BIT(3)
#define DMA_INTERRUPT_STATUS_DC4IS                       BIT(4)
#define DMA_INTERRUPT_STATUS_DC5IS                       BIT(5)
#define DMA_INTERRUPT_STATUS_DC6IS                       BIT(6)
#define DMA_INTERRUPT_STATUS_DC7IS                       BIT(7)
#define DMA_INTERRUPT_STATUS_DC15TC8IS                   GENMASK(15, 8)
#define DMA_INTERRUPT_STATUS_MTLIS                       BIT(16)
#define DMA_INTERRUPT_STATUS_MACIS                       BIT(17)
#define AXI_TX_AR_ACE_CONTROL                            0x3010
#define AXI_TX_AR_ACE_CONTROL_TDRC                       GENMASK(3, 0)
#define AXI_TX_AR_ACE_CONTROL_TDRD                       GENMASK(5, 4)
#define AXI_TX_AR_ACE_CONTROL_TEC                        GENMASK(11, 8)
#define AXI_TX_AR_ACE_CONTROL_TED                        GENMASK(13, 12)
#define AXI_TX_AR_ACE_CONTROL_THC                        GENMASK(19, 16)
#define AXI_TX_AR_ACE_CONTROL_THD                        GENMASK(21, 20)
#define AXI_RX_AW_ACE_CONTROL                            0x3018
#define AXI_RX_AW_ACE_CONTROL_RDWC                       GENMASK(3, 0)
#define AXI_RX_AW_ACE_CONTROL_RDWD                       GENMASK(5, 4)
#define AXI_RX_AW_ACE_CONTROL_RPC                        GENMASK(11, 8)
#define AXI_RX_AW_ACE_CONTROL_RPD                        GENMASK(13, 12)
#define AXI_RX_AW_ACE_CONTROL_RHC                        GENMASK(19, 16)
#define AXI_RX_AW_ACE_CONTROL_RHD                        GENMASK(21, 20)
#define AXI_RX_AW_ACE_CONTROL_RDC                        GENMASK(27, 24)
#define AXI_RX_AW_ACE_CONTROL_RDD                        GENMASK(29, 28)
#define AXI_TXRX_AWAR_ACE_CONTROL                        0x301C
#define AXI_TXRX_AWAR_ACE_CONTROL_TDWC                   GENMASK(3, 0)
#define AXI_TXRX_AWAR_ACE_CONTROL_TDWD                   GENMASK(5, 4)
#define AXI_TXRX_AWAR_ACE_CONTROL_RDRC                   GENMASK(11, 8)
#define AXI_TXRX_AWAR_ACE_CONTROL_RDRD                   GENMASK(13, 12)
#define AXI_TXRX_AWAR_ACE_CONTROL_RDP                    GENMASK(18, 16)
#define AXI_TXRX_AWAR_ACE_CONTROL_WRP                    GENMASK(22, 20)
#define DMA_DEBUG_STATUS0                                0x3020
#define DMA_DEBUG_STATUS0_AXWHSTS                        BIT(0)
#define DMA_DEBUG_STATUS0_AXRHSTS                        BIT(1)
#define DMA_DEBUG_STATUS1                                0x3024
#define DMA_DEBUG_STATUS1_TDAS                           GENMASK(7, 0)
#define DMA_DEBUG_STATUS3                                0x302C
#define DMA_DEBUG_STATUS3_RDAS                           GENMASK(7, 0)
#define DMA_TX_EDMA_CONTROL                              0x3040
#define DMA_TX_EDMA_CONTROL_TDPS                         GENMASK(1, 0)
#define DMA_TX_EDMA_CONTROL_TEDM                         GENMASK(31, 30)
#define DMA_RX_EDMA_CONTROL                              0x3044
#define DMA_RX_EDMA_CONTROL_RDPS                         GENMASK(1, 0)
#define DMA_RX_EDMA_CONTROL_REDM                         GENMASK(31, 30)
#define AXI_LPI_ENTRY_INTERVAL                           0x3050
#define AXI_LPI_ENTRY_INTERVAL_LPIEI                     GENMASK(3, 0)
#define DMA_TBS_CTRL0                                    0x3054
#define DMA_TBS_CTRL0_FTOV                               BIT(0)
#define DMA_TBS_CTRL0_FGOS                               GENMASK(6, 4)
#define DMA_TBS_CTRL0_FTOS                               GENMASK(31, 8)
#define DMA_TBS_CTRL1                                    0x3058
#define DMA_TBS_CTRL1_FTOV                               BIT(0)
#define DMA_TBS_CTRL1_FGOS                               GENMASK(6, 4)
#define DMA_TBS_CTRL1_FTOS                               GENMASK(31, 8)
#define DMA_TBS_CTRL2                                    0x305C
#define DMA_TBS_CTRL2_FTOV                               BIT(0)
#define DMA_TBS_CTRL2_FGOS                               GENMASK(6, 4)
#define DMA_TBS_CTRL2_FTOS                               GENMASK(31, 8)
#define DMA_TBS_CTRL3                                    0x3060
#define DMA_TBS_CTRL3_FTOV                               BIT(0)
#define DMA_TBS_CTRL3_FGOS                               GENMASK(6, 4)
#define DMA_TBS_CTRL3_FTOS                               GENMASK(31, 8)
#define DMA_SAFETY_INTERRUPT_STATUS                      0x3064
#define DMA_SAFETY_INTERRUPT_STATUS_DECIS                BIT(0)
#define DMA_SAFETY_INTERRUPT_STATUS_DEUIS                BIT(1)
#define DMA_SAFETY_INTERRUPT_STATUS_AMCIS                BIT(2)
#define DMA_SAFETY_INTERRUPT_STATUS_AMUIS                BIT(3)
#define DMA_SAFETY_INTERRUPT_STATUS_ASCIS                BIT(4)
#define DMA_SAFETY_INTERRUPT_STATUS_ASUIS                BIT(5)
#define DMA_SAFETY_INTERRUPT_STATUS_MSCIS                BIT(28)
#define DMA_SAFETY_INTERRUPT_STATUS_MSUIS                BIT(29)
#define DMA_SAFETY_INTERRUPT_STATUS_MCSIS                BIT(31)
#define DMA_ECC_INTERRUPT_ENABLE                         0x3068
#define DMA_ECC_INTERRUPT_ENABLE_DCEIE                   BIT(1)
#define DMA_ECC_INTERRUPT_STATUS                         0x306C
#define DMA_ECC_INTERRUPT_STATUS_DCES                    BIT(4)
#define DMA_ECC_INTERRUPT_STATUS_DAMS                    BIT(5)
#define DMA_ECC_INTERRUPT_STATUS_DUES                    BIT(6)
#define DMA_DPP_CONTROL                                  0x3070
#define DMA_DPP_CONTROL_IPETD                            GENMASK(7, 0)
#define DMA_DPP_CONTROL_IPERD                            GENMASK(23, 16)
#define DMA_DPP_INTERRUPT_STATUS                         0x3074
#define DMA_DPP_INTERRUPT_STATUS_TDPES                   GENMASK(7, 0)
#define DMA_DPP_INTERRUPT_STATUS_RDPES                   GENMASK(23, 16)
#define DMA_CH_IND_CTRL                                  0x3080
#define DMA_CH_IND_CTRL_OB                               BIT(0)
#define DMA_CH_IND_CTRL_CT                               BIT(1)
#define DMA_CH_IND_CTRL_AUTO                             GENMASK(5, 4)
#define DMA_CH_IND_CTRL_AOFF                             GENMASK(11, 8)
#define DMA_CH_IND_CTRL_MSEL                             GENMASK(19, 16)
#define DMA_CH_IND_DATA                                  0x3084
#define DMA_CH_IND_DATA_WT                               GENMASK(6, 0)
#define DMA_SFTY_IND_CTRL                                0x3088
#define DMA_SFTY_IND_CTRL_OB                             BIT(0)
#define DMA_SFTY_IND_CTRL_CT                             BIT(1)
#define DMA_SFTY_IND_CTRL_AUTO                           GENMASK(5, 4)
#define DMA_SFTY_IND_CTRL_AOFF                           GENMASK(11, 8)
#define DMA_SFTY_IND_CTRL_MSEL                           GENMASK(19, 16)
#define DMA_SFTY_IND_CTRL_DAPS                           GENMASK(23, 22)
#define DMA_SFTY_IND_DATA                                0x308C
#define DMA_CHi_CONTROL(i)                               (0x3100 + i * 0x80)
#define DMA_CHi_CONTROL_PBLX8                            BIT(16)
#define DMA_CHi_CONTROL_DSL                              GENMASK(20, 18)
#define DMA_CHi_CONTROL_SPH                              BIT(24)
#define DMA_CHi_TX_CONTROL(i)                            (0x3104 + i * 0x80)
#define DMA_CHi_TX_CONTROL_ST                            BIT(0)
#define DMA_CHi_TX_CONTROL_TXPBL                         GENMASK(21, 16)
#define DMA_CHi_TX_CONTROL_TQOS                          GENMASK(27, 24)
#define DMA_CHi_TX_CONTROL_EDSE                          BIT(28)
#define DMA_CHi_TX_CONTROL_TFSEL                         GENMASK(30, 29)
#define DMA_CHi_RX_CONTROL(i)                            (0x3108 + i * 0x80)
#define DMA_CHi_RX_CONTROL_SR                            BIT(0)
#define DMA_CHi_RX_CONTROL_RBSZ                          GENMASK(14, 4)
#define DMA_CHi_RX_CONTROL_RXPBL                         GENMASK(21, 16)
#define DMA_CHi_RX_CONTROL_RQOS                          GENMASK(27, 24)
#define DMA_CHi_RX_CONTROL_RPF                           BIT(31)
#define DMA_CHi_SLOT_FUNCTION_CONTROL_STATUS(i)          (0x310C + i * 0x80)
#define DMA_CHi_SLOT_FUNCTION_CONTROL_STATUS_ESC         BIT(0)
#define DMA_CHi_SLOT_FUNCTION_CONTROL_STATUS_ASC         BIT(1)
#define DMA_CHi_SLOT_FUNCTION_CONTROL_STATUS_RSN         GENMASK(19, 16)
#define DMA_CHi_TXDESC_LIST_LADDRESS(i)                  (0x3114 + i * 0x80)
#define DMA_CHi_TXDESC_LIST_HADDRESS(i)                  (0x3118 + i * 0x80)
#define DMA_CHi_RXDESC_LIST_LADDRESS(i)                  (0x311C + i * 0x80)
#define DMA_CHi_RXDESC_LIST_HADDRESS(i)                  (0x3120 + i * 0x80)
#define DMA_CHi_TXDESC_TAIL_LPOINTER(i)                  (0x3124 + i * 0x80)
#define DMA_CHi_RXDESC_TAIL_LPOINTER(i)                  (0x312C + i * 0x80)
#define DMA_CHi_TX_CONTROL2(i)                           (0x3130 + i * 0x80)
#define DMA_CHi_TXDESC_TAIL_LPOINTER(i)                  (0x3124 + i * 0x80)
#define DMA_CHi_TX_CONTROL2_TDRL                         GENMASK(15, 0)
#define DMA_CHi_TX_CONTROL2_ORRQ                         BIT(24)
#define DMA_CHi_RX_CONTROL2(i)                           (0x3134 + i * 0x80)
#define DMA_CHi_RX_CONTROL2_RDRL                         GENMASK(15, 0)
#define DMA_CHi_RX_CONTROL2_ARBS                         GENMASK(23, 17)
#define DMA_CHi_RX_CONTROL2_OWRQ                         BIT(24)
#define DMA_CHi_INTERRUPT_ENABLE(i)                      (0x3138 + i * 0x80)
#define DMA_CHi_INTERRUPT_ENABLE_TIE                     BIT(0)
#define DMA_CHi_INTERRUPT_ENABLE_TXSE                    BIT(1)
#define DMA_CHi_INTERRUPT_ENABLE_TBUE                    BIT(2)
#define DMA_CHi_INTERRUPT_ENABLE_RIE                     BIT(6)
#define DMA_CHi_INTERRUPT_ENABLE_RBUE                    BIT(7)
#define DMA_CHi_INTERRUPT_ENABLE_RSE                     BIT(8)
#define DMA_CHi_INTERRUPT_ENABLE_DDEE                    BIT(9)
#define DMA_CHi_INTERRUPT_ENABLE_FBEE                    BIT(12)
#define DMA_CHi_INTERRUPT_ENABLE_CDEE                    BIT(13)
#define DMA_CHi_INTERRUPT_ENABLE_AIE                     BIT(14)
#define DMA_CHi_INTERRUPT_ENABLE_NIE                     BIT(15)
#define DMA_CHi_RX_INTERRUPT_WATCHDOG_TIMER(i)           (0x313C + i * 0x80)
#define DMA_CHi_RX_INTERRUPT_WATCHDOG_TIMER_RWT          GENMASK(7, 0)
#define DMA_CHi_RX_INTERRUPT_WATCHDOG_TIMER_RWTU         GENMASK(13, 12)
#define DMA_CHi_RX_INTERRUPT_WATCHDOG_TIMER_RBCT         GENMASK(25, 16)
#define DMA_CHi_RX_INTERRUPT_WATCHDOG_TIMER_PSEL         BIT(31)
#define DMA_CHi_CURRENT_APP_TXDESC_L(i)                  (0x3144 + i * 0x80)
#define DMA_CHi_CURRENT_APP_RXDESC_L(i)                  (0x314C + i * 0x80)
#define DMA_CHi_CURRENT_APP_TXBUFFER_L(i)                (0x3154 + i * 0x80)
#define DMA_CHi_CURRENT_APP_RXBUFFER_L(i)                (0x315C + i * 0x80)
#define DMA_CHi_STATUS(i)                                (0x3160 + i * 0x80)
#define DMA_CHi_STATUS_TI                                BIT(0)
#define DMA_CHi_STATUS_TPS                               BIT(1)
#define DMA_CHi_STATUS_TBU                               BIT(2)
#define DMA_CHi_STATUS_RI                                BIT(6)
#define DMA_CHi_STATUS_RBU                               BIT(7)
#define DMA_CHi_STATUS_RPS                               BIT(8)
#define DMA_CHi_STATUS_DDE                               BIT(9)
#define DMA_CHi_STATUS_FBE                               BIT(12)
#define DMA_CHi_STATUS_CDE                               BIT(13)
#define DMA_CHi_STATUS_AIS                               BIT(14)
#define DMA_CHi_STATUS_NIS                               BIT(15)
#define DMA_CHi_STATUS_TEB                               GENMASK(18, 16)
#define DMA_CHi_STATUS_REB                               GENMASK(21, 19)
#define DMA_CHi_DEBUG_STATUS(i)                          (0x3164 + i * 0x80)
#define DMA_CHi_DEBUG_STATUS_TDFS                        GENMASK(2, 0)
#define DMA_CHi_DEBUG_STATUS_TDXS                        GENMASK(5, 3)
#define DMA_CHi_DEBUG_STATUS_TDRS                        GENMASK(7, 6)
#define DMA_CHi_DEBUG_STATUS_TDTS                        GENMASK(11, 8)
#define DMA_CHi_DEBUG_STATUS_TDWS                        GENMASK(14, 12)
#define DMA_CHi_DEBUG_STATUS_RDFS                        GENMASK(18, 16)
#define DMA_CHi_DEBUG_STATUS_RDTS                        GENMASK(27, 19)
#define DMA_CHi_DEBUG_STATUS_RDWS                        GENMASK(30, 28)
#define DMA_CHi_DESC_MEM_CACHE_FILL_LEVEL(i)             (0x3168 + i * 0x80)
#define DMA_CHi_DESC_MEM_CACHE_FILL_LEVEL_TX_FILL_LVL    GENMASK(6, 0)
#define DMA_CHi_DESC_MEM_CACHE_FILL_LEVEL_RX_FILL_LVL    GENMASK(22, 16)
#define DMA_CHi_MISS_PACKET_CNT(i)                       (0x316C + i * 0x80)
#define DMA_CHi_MISS_PACKET_CNT_MFC                      GENMASK(10, 0)
#define DMA_CHi_MISS_PACKET_CNT_MFCO                     BIT(15)
#define DMA_CHi_TX_DATA_XFER_RING_OFFSET(i)              (0x3170 + i * 0x80)
#define DMA_CHi_TX_DATA_XFER_RING_OFFSET_DESC_OFFSET     GENMASK(15, 0)
#define DMA_CHi_RX_DATA_XFER_RING_OFFSET(i)              (0x3174 + i * 0x80)
#define DMA_CHi_RX_DATA_XFER_RING_OFFSET_DESC_OFFSET     GENMASK(15, 0)
#define DMA_CHi_TX_DESC_WRITE_RING_OFFSET(i)             (0x3178 + i * 0x80)
#define DMA_CHi_TX_DESC_WRITE_RING_OFFSET_DESC_OFFSET    GENMASK(15, 0)
#define DMA_CHi_RX_DESC_WRITE_RING_OFFSET(i)             (0x317C + i * 0x80)
#define DMA_CHi_RX_DESC_WRITE_RING_OFFSET_DESC_OFFSET    GENMASK(15, 0)

#endif
